<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class BankInternalsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('bank_internals')->delete();
        
        \DB::table('bank_internals')->insert(array (
            0 => 
            array (
                'id' => 2,
                'code' => 'BRI USI',
                'type' => 'bank',
                'nama_bank' => 'BRI',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT UNITED SHIPPING INDONESIA',
                'created_at' => '2022-12-16 02:05:35',
                'updated_at' => '2023-03-17 16:53:42',
                'deleted_at' => NULL,
                'no_rekening' => '212004',
            ),
            1 => 
            array (
                'id' => 17,
                'code' => 'BCA USI',
                'type' => 'bank',
                'nama_bank' => 'BCA',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT UNITED SHIPPING INDONESIA',
                'created_at' => '2023-01-17 10:39:13',
                'updated_at' => '2023-03-17 16:30:03',
                'deleted_at' => NULL,
                'no_rekening' => '829.056.7778',
            ),
            2 => 
            array (
                'id' => 23,
                'code' => 'MDR',
                'type' => 'bank',
                'nama_bank' => 'Mandiri',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT United Shipping Indonesia',
                'created_at' => '2023-03-17 16:10:46',
                'updated_at' => '2023-03-17 16:27:44',
                'deleted_at' => NULL,
                'no_rekening' => '141.00.01419992',
            ),
            3 => 
            array (
                'id' => 24,
                'code' => 'BSM',
                'type' => 'bank',
                'nama_bank' => 'Bank Syariah Mandiri',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT United Shipping Indonesia',
                'created_at' => '2023-03-17 16:24:39',
                'updated_at' => '2023-03-17 16:43:55',
                'deleted_at' => NULL,
                'no_rekening' => '7008557246',
            ),
            4 => 
            array (
                'id' => 25,
                'code' => 'BSM1',
                'type' => 'bank',
                'nama_bank' => 'Bank Syariah Mandiri',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT United Shipping Indonesia',
                'created_at' => '2023-03-17 16:35:09',
                'updated_at' => '2023-03-17 16:35:09',
                'deleted_at' => NULL,
                'no_rekening' => '7025880735',
            ),
            5 => 
            array (
                'id' => 26,
                'code' => 'DNM',
                'type' => 'bank',
                'nama_bank' => 'Danamon',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT USI',
                'created_at' => '2023-03-17 16:43:47',
                'updated_at' => '2023-03-17 16:43:47',
                'deleted_at' => NULL,
                'no_rekening' => '3510186962',
            ),
            6 => 
            array (
                'id' => 27,
                'code' => 'MDR1',
                'type' => 'bank',
                'nama_bank' => 'Mandiri',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT USI',
                'created_at' => '2023-03-17 16:44:41',
                'updated_at' => '2023-03-17 16:44:41',
                'deleted_at' => NULL,
                'no_rekening' => '141.00.01419993',
            ),
            7 => 
            array (
                'id' => 28,
                'code' => 'BSM3',
                'type' => 'bank',
            'nama_bank' => 'Bank Syariah Mandiri (Modal Kerja)',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT USI',
                'created_at' => '2023-03-17 16:49:46',
                'updated_at' => '2023-03-17 16:49:46',
                'deleted_at' => NULL,
                'no_rekening' => '212001',
            ),
            8 => 
            array (
                'id' => 29,
                'code' => 'BSM2',
                'type' => 'bank',
            'nama_bank' => 'Bank Syariah Mandiri (PRK)',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT USI',
                'created_at' => '2023-03-17 16:51:09',
                'updated_at' => '2023-03-17 16:52:10',
                'deleted_at' => NULL,
                'no_rekening' => '7108953211',
            ),
            9 => 
            array (
                'id' => 30,
                'code' => 'STC',
                'type' => 'bank',
                'nama_bank' => 'Standard Chartered Bank',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT USI',
                'created_at' => '2023-03-17 16:53:08',
                'updated_at' => '2023-03-17 16:53:08',
                'deleted_at' => NULL,
                'no_rekening' => '212003',
            ),
            10 => 
            array (
                'id' => 31,
                'code' => 'HOC',
                'type' => 'bank',
                'nama_bank' => 'Kas Pusat',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT USI',
                'created_at' => '2023-03-17 16:57:01',
                'updated_at' => '2023-03-17 16:57:01',
                'deleted_at' => NULL,
                'no_rekening' => '111101',
            ),
            11 => 
            array (
                'id' => 32,
                'code' => 'HOPC',
                'type' => 'bank',
                'nama_bank' => 'Petty Cash Pusat',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT USI',
                'created_at' => '2023-03-17 16:57:40',
                'updated_at' => '2023-03-17 16:57:40',
                'deleted_at' => NULL,
                'no_rekening' => '111102',
            ),
            12 => 
            array (
                'id' => 33,
                'code' => 'SMC',
                'type' => 'bank',
                'nama_bank' => 'Kas Samarinda',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT USI Smd',
                'created_at' => '2023-03-17 16:58:25',
                'updated_at' => '2023-03-17 16:58:25',
                'deleted_at' => NULL,
                'no_rekening' => '111103',
            ),
            13 => 
            array (
                'id' => 34,
                'code' => 'PLC',
                'type' => 'bank',
                'nama_bank' => 'Kas Palembang',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT USI Plm',
                'created_at' => '2023-03-17 16:59:08',
                'updated_at' => '2023-03-20 16:56:00',
                'deleted_at' => NULL,
                'no_rekening' => '111104',
            ),
            14 => 
            array (
                'id' => 35,
                'code' => 'BCA.CV',
                'type' => 'bank',
                'nama_bank' => 'BCA',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'CV. SENTRAL JAYA TEHNIK',
                'created_at' => '2023-03-21 11:53:29',
                'updated_at' => '2023-03-21 11:53:29',
                'deleted_at' => NULL,
                'no_rekening' => '464.502.9888',
            ),
            15 => 
            array (
                'id' => 36,
                'code' => 'BCA.CV2',
                'type' => 'bank',
                'nama_bank' => 'BCA',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'CV. PRIMA SOLUSI TEKNIK',
                'created_at' => '2023-03-21 11:54:23',
                'updated_at' => '2023-03-21 11:54:23',
                'deleted_at' => NULL,
                'no_rekening' => '464.024.4777',
            ),
            16 => 
            array (
                'id' => 37,
                'code' => 'BCA PTE',
                'type' => 'bank',
                'nama_bank' => 'BCA',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT. USI PETROTRANS ENERGI',
                'created_at' => '2023-03-24 11:22:26',
                'updated_at' => '2023-03-24 11:22:26',
                'deleted_at' => NULL,
                'no_rekening' => '829.187.7788',
            ),
            17 => 
            array (
                'id' => 38,
                'code' => 'PMTE',
                'type' => 'bank',
                'nama_bank' => 'PERMATA',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT. USI PETROTRANS ENERGI',
                'created_at' => '2023-03-24 11:30:06',
                'updated_at' => '2023-05-30 16:22:14',
                'deleted_at' => NULL,
                'no_rekening' => '702.492.750',
            ),
            18 => 
            array (
                'id' => 39,
                'code' => 'BRIS2',
                'type' => 'bank',
                'nama_bank' => 'BRI',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT. USI PETROTRANS SAMUDRA',
                'created_at' => '2023-05-29 13:44:00',
                'updated_at' => '2023-05-30 16:19:23',
                'deleted_at' => NULL,
                'no_rekening' => '0096.0100.3097.566',
            ),
            19 => 
            array (
                'id' => 40,
                'code' => 'BRIS1',
                'type' => 'bank',
                'nama_bank' => 'BRI',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT. USI PETROTRANS SAMUDRA',
                'created_at' => '2023-05-29 13:47:16',
                'updated_at' => '2023-05-30 16:19:47',
                'deleted_at' => NULL,
                'no_rekening' => '0096.0100.3098.562',
            ),
            20 => 
            array (
                'id' => 41,
                'code' => 'BCAS1',
                'type' => 'bank',
                'nama_bank' => 'BCA',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT. USI PETROTRANS SAMUDRA',
                'created_at' => '2023-05-29 13:49:06',
                'updated_at' => '2023-05-30 16:20:29',
                'deleted_at' => NULL,
                'no_rekening' => '829.117.7778',
            ),
            21 => 
            array (
                'id' => 42,
                'code' => 'BCAPNE',
                'type' => 'bank',
                'nama_bank' => 'BCA',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT. PETRONUSA NIAGA ENERGI',
                'created_at' => '2023-05-29 14:10:18',
                'updated_at' => '2023-05-30 16:21:36',
                'deleted_at' => NULL,
                'no_rekening' => '788.072.7600',
            ),
            22 => 
            array (
                'id' => 43,
                'code' => 'BCAS2',
                'type' => 'bank',
            'nama_bank' => 'BCA (USD)',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT. USI PETROTRANS SAMUDRA',
                'created_at' => '2023-05-29 14:11:38',
                'updated_at' => '2023-05-30 16:21:04',
                'deleted_at' => NULL,
                'no_rekening' => '829.139.7778',
            ),
            23 => 
            array (
                'id' => 44,
                'code' => 'KKSJT',
                'type' => 'kas',
                'nama_bank' => 'KAS CV.SJT',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'CV. SENTRAL JAYA TEKNIK',
                'created_at' => '2023-05-29 14:12:31',
                'updated_at' => '2023-05-30 16:08:10',
                'deleted_at' => NULL,
                'no_rekening' => '000000',
            ),
            24 => 
            array (
                'id' => 45,
                'code' => 'KKPST',
                'type' => 'kas',
                'nama_bank' => 'KAS CV. PST',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'CV. PRIMA SOLUSI TEKNIK',
                'created_at' => '2023-05-29 14:13:29',
                'updated_at' => '2023-05-30 16:08:47',
                'deleted_at' => NULL,
                'no_rekening' => '00000',
            ),
            25 => 
            array (
                'id' => 46,
                'code' => 'KKPTSSMD',
                'type' => 'kas',
                'nama_bank' => 'KAS KECIL PTS - SMD',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT. USI PETROTRANS SAMUDRA',
                'created_at' => '2023-05-29 14:14:15',
                'updated_at' => '2023-05-30 16:09:30',
                'deleted_at' => NULL,
                'no_rekening' => '00',
            ),
            26 => 
            array (
                'id' => 47,
                'code' => 'KKPTSSBY',
                'type' => 'kas',
                'nama_bank' => 'KAS KECIL PTS - SBY',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT. USI PETROTRANS SAMUDRA',
                'created_at' => '2023-05-29 14:15:19',
                'updated_at' => '2023-05-30 16:10:58',
                'deleted_at' => NULL,
                'no_rekening' => '00000000',
            ),
            27 => 
            array (
                'id' => 48,
                'code' => 'KKPNESBY',
                'type' => 'kas',
                'nama_bank' => 'KAS KECIL PNE - SBY',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT. PETRONUSA NIAGA ENERGI',
                'created_at' => '2023-05-29 14:18:04',
                'updated_at' => '2023-05-30 16:11:26',
                'deleted_at' => NULL,
                'no_rekening' => '000',
            ),
            28 => 
            array (
                'id' => 49,
                'code' => 'OCBCBMEUSD',
                'type' => 'bank',
            'nama_bank' => 'OCBC NISP (USD)',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT. Bumi Mandala Energi',
                'created_at' => '2023-06-15 16:16:52',
                'updated_at' => '2023-06-15 16:16:52',
                'deleted_at' => NULL,
            'no_rekening' => '123.456.7899 (USD)',
            ),
            29 => 
            array (
                'id' => 50,
                'code' => 'OCBCBMEIDR',
                'type' => 'bank',
            'nama_bank' => 'OCBC NISP (IDR)',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT. Bumi Mandala Energi',
                'created_at' => '2023-06-15 16:18:47',
                'updated_at' => '2023-06-15 16:18:47',
                'deleted_at' => NULL,
            'no_rekening' => '123.456.8910 (IDR)',
            ),
            30 => 
            array (
                'id' => 51,
                'code' => 'PMT1',
                'type' => 'bank',
                'nama_bank' => 'PERMATA SYAHRIAH GIRO-IDR',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT UNITED SHIPPING INDONESIA',
                'created_at' => '2023-06-27 17:05:47',
                'updated_at' => '2023-06-27 17:06:25',
                'deleted_at' => NULL,
                'no_rekening' => '702.358.779',
            ),
            31 => 
            array (
                'id' => 52,
                'code' => 'BSM4',
                'type' => 'bank',
                'nama_bank' => 'BANK SYARIAH MANDIRI USI IDR',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT. UNITED SHIPPING INDONESIA',
                'created_at' => '2023-06-27 17:48:42',
                'updated_at' => '2023-06-27 19:47:09',
                'deleted_at' => NULL,
                'no_rekening' => '7205555007',
            ),
            32 => 
            array (
                'id' => 53,
                'code' => 'MDR2',
                'type' => 'bank',
                'nama_bank' => 'MANDIRI USD',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT UNITED SHIPPING INDONESIA',
                'created_at' => '2023-06-27 17:54:47',
                'updated_at' => '2023-06-27 17:54:47',
                'deleted_at' => NULL,
                'no_rekening' => '140.00.12688124',
            ),
            33 => 
            array (
                'id' => 54,
                'code' => 'PMT2',
                'type' => 'bank',
                'nama_bank' => 'PERMATA USI 6990',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT UNITED SHIPPING INDONESIA',
                'created_at' => '2023-06-27 18:02:12',
                'updated_at' => '2023-06-27 18:02:12',
                'deleted_at' => NULL,
                'no_rekening' => '293.000.6990',
            ),
            34 => 
            array (
                'id' => 55,
                'code' => 'SCB1',
                'type' => 'bank',
                'nama_bank' => 'SCB IDR 2189',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT UNITED SHIPPING INDONESIA',
                'created_at' => '2023-06-27 18:05:06',
                'updated_at' => '2023-06-27 18:05:06',
                'deleted_at' => NULL,
                'no_rekening' => '021.05472189',
            ),
            35 => 
            array (
                'id' => 56,
                'code' => 'BNI1',
                'type' => 'bank',
                'nama_bank' => 'BNI USI IDR 6369',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT UNITED SHIPPING INDONESIA',
                'created_at' => '2023-06-27 18:09:21',
                'updated_at' => '2023-06-27 18:09:21',
                'deleted_at' => NULL,
                'no_rekening' => '168.6666.369',
            ),
            36 => 
            array (
                'id' => 57,
                'code' => 'BSM5',
                'type' => 'bank',
                'nama_bank' => 'BANK SYARIAH MANDIRI USI IDR',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT UNITED SHIPPING INDONESIA',
                'created_at' => '2023-06-27 19:50:03',
                'updated_at' => '2023-06-27 19:50:03',
                'deleted_at' => NULL,
                'no_rekening' => '7108949467',
            ),
            37 => 
            array (
                'id' => 58,
                'code' => 'MNC1',
                'type' => 'bank',
                'nama_bank' => 'MNC USI IDR 4334',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT UNITED SHIPPING INDONESIA',
                'created_at' => '2023-06-27 19:55:12',
                'updated_at' => '2023-06-27 19:55:12',
                'deleted_at' => NULL,
                'no_rekening' => '1000.108.9000.4334',
            ),
            38 => 
            array (
                'id' => 59,
                'code' => 'BRI1',
                'type' => 'bank',
                'nama_bank' => 'BRI USI GIRO IDR 3306',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT UNITED SHIPPING INDONESIA',
                'created_at' => '2023-06-27 19:59:27',
                'updated_at' => '2023-06-27 19:59:27',
                'deleted_at' => NULL,
                'no_rekening' => '0096.0100.4263.306',
            ),
            39 => 
            array (
                'id' => 60,
                'code' => 'BRI2',
                'type' => 'bank',
                'nama_bank' => 'BRI USI IDR 5308',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT UNITED SHIPPING INDONESIA',
                'created_at' => '2023-06-27 20:02:00',
                'updated_at' => '2023-06-27 20:02:00',
                'deleted_at' => NULL,
                'no_rekening' => '0096.0100.4285.308',
            ),
            40 => 
            array (
                'id' => 61,
                'code' => 'BRI3',
                'type' => 'bank',
                'nama_bank' => 'BRI PUSAT USI IDR 2565',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT UNITED SHIPPING INDONESIA',
                'created_at' => '2023-06-27 20:04:58',
                'updated_at' => '2023-06-27 20:04:58',
                'deleted_at' => NULL,
                'no_rekening' => '0096.0100.2872.565',
            ),
            41 => 
            array (
                'id' => 62,
                'code' => 'BRI4',
                'type' => 'bank',
                'nama_bank' => 'BRI SMD USI IDR 1569',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT UNITED SHIPPING INDONESIA',
                'created_at' => '2023-06-27 20:07:59',
                'updated_at' => '2023-06-27 20:07:59',
                'deleted_at' => NULL,
                'no_rekening' => '0096.0100.2871.569',
            ),
            42 => 
            array (
                'id' => 63,
                'code' => 'OCBC1',
                'type' => 'bank',
                'nama_bank' => 'OCBC NISP PAYROLL IDR',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT UNITED SHIPPING INDONESIA',
                'created_at' => '2023-06-27 20:10:31',
                'updated_at' => '2023-06-27 20:10:31',
                'deleted_at' => NULL,
                'no_rekening' => '550.8000.98877',
            ),
            43 => 
            array (
                'id' => 64,
                'code' => 'PMT3',
                'type' => 'bank',
                'nama_bank' => 'PERMATA USD USI 4509',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT UNITED SHIPPING INDONESIA',
                'created_at' => '2023-06-27 20:12:48',
                'updated_at' => '2023-06-27 20:12:48',
                'deleted_at' => NULL,
                'no_rekening' => '701.704.509',
            ),
            44 => 
            array (
                'id' => 65,
                'code' => 'MDR3',
                'type' => 'bank',
                'nama_bank' => 'MANDIRI USI IDR 2227',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT UNITED SHIPPING INDONESIA',
                'created_at' => '2023-06-27 20:15:30',
                'updated_at' => '2023-06-27 20:15:30',
                'deleted_at' => NULL,
                'no_rekening' => '142.00.88722227',
            ),
            45 => 
            array (
                'id' => 66,
                'code' => 'BRI5',
                'type' => 'bank',
                'nama_bank' => 'BRI INTEREST USI IDR 6303',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT UNITED SHIPPING INDONESIA',
                'created_at' => '2023-06-27 20:18:21',
                'updated_at' => '2023-06-27 20:18:21',
                'deleted_at' => NULL,
                'no_rekening' => '0096.0100.5126.303',
            ),
            46 => 
            array (
                'id' => 67,
                'code' => 'BCA USI2',
                'type' => 'bank',
                'nama_bank' => 'BCA GALAXY USI IDR 9899',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT UNITED SHIPPING INDONESIA',
                'created_at' => '2023-06-27 20:24:17',
                'updated_at' => '2023-06-27 20:24:17',
                'deleted_at' => NULL,
                'no_rekening' => '788.118.9899',
            ),
            47 => 
            array (
                'id' => 68,
                'code' => 'PAN1',
                'type' => 'bank',
                'nama_bank' => 'PANIN USI USD 7878',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT UNITED SHIPPING INDONESIA',
                'created_at' => '2023-06-28 09:24:04',
                'updated_at' => '2023-06-28 09:24:04',
                'deleted_at' => NULL,
                'no_rekening' => '400.600.7878',
            ),
            48 => 
            array (
                'id' => 69,
                'code' => 'HSBC1',
                'type' => 'bank',
                'nama_bank' => 'HSBC USI USD 3115',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT UNITED SHIPPING INDONESIA',
                'created_at' => '2023-06-28 09:27:24',
                'updated_at' => '2023-06-28 09:27:24',
                'deleted_at' => NULL,
                'no_rekening' => '004.200.333.115',
            ),
            49 => 
            array (
                'id' => 70,
                'code' => 'BRIS3',
                'type' => 'bank',
                'nama_bank' => 'BRI PTS 9302',
                'branch_id' => 1,
                'coa_id' => NULL,
                'on_behalf_of' => 'PT. USI PETROTRANS SAMUDRA',
                'created_at' => '2023-06-28 11:38:26',
                'updated_at' => '2023-06-28 11:38:26',
                'deleted_at' => NULL,
                'no_rekening' => '0096.0100.4729.302',
            ),
        ));
        
        
    }
}