<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CustomersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('customers')->delete();
        
        \DB::table('customers')->insert(array (
            0 => 
            array (
                'id' => 1,
                'code' => 'CUS-IXX-001',
                'nama' => 'PT. INFION',
                'alamat' => 'Jl. Raya Kasri 153, RT02 RW02, Tawang Rejo, Pandaan, Pasuruan, Jawa Timur',
                'npwp' => '02.513.191.3-624.000',
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => '08179715424',
                'lost_tolerance' => '0.3000',
                'lost_tolerance_type' => 'percent',
                'website' => NULL,
                'term_of_payment' => 'by days',
                'top_days' => 30,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:25:47',
                'updated_at' => '2023-10-16 19:12:52',
                'type' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'code' => 'CUS-PPH-001',
            'nama' => 'PT. PERUSAHAAN PERSEROAN (PERSERO) PT. HUTAMA KARYA',
                'alamat' => 'JL LETJEN MT HARYONO KAV NO. 8 RT:012 RW:011 Kel.CIPINANG CEMPEDAK Kec.JATINEGARA Kota/Kab.JAKARTA T',
                'npwp' => '01.001.611.1-093.000',
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => '0.0000',
                'lost_tolerance_type' => NULL,
                'website' => NULL,
                'term_of_payment' => 'cash',
                'top_days' => 0,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:25:47',
                'updated_at' => '2023-10-16 19:20:51',
                'type' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'code' => 'CUS-UPS-001',
                'nama' => 'PT. USI PETROTRANS SAMUDRA',
                'alamat' => 'Gondosuli No.8 Rt.005 Rw.006 Kel.Ketabang Kec.Genteng, Surabaya, Jawa Timur',
                'npwp' => '92.117.834.9-611.000',
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => '0.0000',
                'lost_tolerance_type' => 'percent',
                'website' => NULL,
                'term_of_payment' => 'by days',
                'top_days' => 30,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:25:48',
                'updated_at' => '2024-03-26 17:33:41',
                'type' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'code' => 'CUS-UPE-001',
                'nama' => 'PT. USI PETROTRANS ENERGI',
                'alamat' => 'Gondosuli No.8 Rt.005 Rw.006 Kel.Ketabang Kec.Genteng, Surabaya, Jawa Timur',
                'npwp' => '92.151.549.0-611.020',
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => '0.0000',
                'lost_tolerance_type' => 'percent',
                'website' => NULL,
                'term_of_payment' => 'by days',
                'top_days' => 30,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:25:50',
                'updated_at' => '2024-03-26 17:33:17',
                'type' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'code' => 'CUS-CDM-001',
                'nama' => 'PT. CIPTA DAVIA MANDIRI',
                'alamat' => 'Gedung Grha Bintang 1st Floor B-C-D Jl. Jend. Sudirman no 423 Damai Bahagia, Balikpapan Selatan, Kot',
                'npwp' => '01.997.572.1-725.000',
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => '0.0030',
                'lost_tolerance_type' => 'percent',
                'website' => NULL,
                'term_of_payment' => 'by days',
                'top_days' => 60,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:25:52',
                'updated_at' => '2024-02-06 18:06:11',
                'type' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'code' => 'CUS-DIL-001',
                'nama' => 'PT. DHARMA INTISAWIT LESTARI',
                'alamat' => 'GRHA DSN Jalan Pulo Ayang Kav.OR 3 Kawasan Industri Pulogadung, Jatinegara, Cakung, Kota Adm. Jakarta Timur, DKI Jakarta 13930',
                'npwp' => '01.821.556.6-004.000',
                'email' => 'hadi.siswanto@dsngroup.co.id',
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => '0.0050',
                'lost_tolerance_type' => 'percent',
                'website' => NULL,
                'term_of_payment' => 'by days',
                'top_days' => 30,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:25:53',
                'updated_at' => '2024-05-13 09:34:07',
                'type' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'code' => 'CUS-JMS-001',
                'nama' => 'PT. JAYA MANDIRI SUKSES',
                'alamat' => 'Gedung Rajawali Place Lt 28. Jl HR Rasuna Said Kav B/4, Setiabudi, Setiabudi,Kota Adm. Jakarta Selatan, DKI Jakarta',
                'npwp' => '02.354.536.1-058.000',
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => '0.0050',
                'lost_tolerance_type' => 'percent',
                'website' => NULL,
                'term_of_payment' => 'by days',
                'top_days' => 60,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:25:54',
                'updated_at' => '2024-03-21 17:50:45',
                'type' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'code' => 'CUS-KAX-001',
                'nama' => 'PT. KARYAPRATAMA AGRISEJAHTERA',
                'alamat' => 'Desa Sei Ayuh Jl Prov RT 05 RW 00, Siayuh, Kelumpang Barat, Kota Baru',
                'npwp' => '01.534.793.3-734.000',
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => '0.0050',
                'lost_tolerance_type' => 'percent',
                'website' => NULL,
                'term_of_payment' => 'by days',
                'top_days' => 60,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:25:57',
                'updated_at' => '2024-01-16 17:52:57',
                'type' => 'trading',
            ),
            8 => 
            array (
                'id' => 9,
                'code' => 'CUS-MAJ-001',
                'nama' => 'PT. MANUNGGAL ADI JAYA',
                'alamat' => 'GEDUNG RAJAWALI PLACE LT.28, JL. HR RASUNA SAID KAV B/4, BLOK SETIA BUDI, SETIABUDI, JAKARTA SELATAN',
                'npwp' => '02.354.534.6-063.000',
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => '0.0050',
                'lost_tolerance_type' => 'percent',
                'website' => NULL,
                'term_of_payment' => 'by days',
                'top_days' => 60,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:25:57',
                'updated_at' => '2024-03-21 18:01:00',
                'type' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'code' => 'CUS-PSX-001',
                'nama' => 'PT. PESONALINTAS SURASEJATI',
                'alamat' => 'GD. NOBLE HOUSE Lt. 12, Jl. DR Ide Anak Agung Gde Agung Kav E 4.2 Sub 6.7 No. 2 Kuningan Timur Setiabudi Jakarta Selatan DKI Jakarta',
                'npwp' => '01.542.024.3-063.000',
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => '0.0050',
                'lost_tolerance_type' => 'percent',
                'website' => NULL,
                'term_of_payment' => 'by days',
                'top_days' => 60,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:25:58',
                'updated_at' => '2024-01-16 18:30:18',
                'type' => 'trading',
            ),
            10 => 
            array (
                'id' => 11,
                'code' => 'CUS-PNE-001',
                'nama' => 'PT. PETRONUSA NIAGA ENERGY',
                'alamat' => 'SKYLOFT SOHO UNIT 1908, JL.Mayjend Sungkono 89, Gunungsari, Dukuh Pakis,Surabaya, Jawa Timur 60224',
                'npwp' => '02.825.575.0-604.004',
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => '0.0000',
                'lost_tolerance_type' => 'percent',
                'website' => NULL,
                'term_of_payment' => 'cash',
                'top_days' => 0,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:25:59',
                'updated_at' => '2024-03-28 22:56:32',
                'type' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'code' => 'CUS-PPA-001',
                'nama' => 'PT. PUTRA PERKASA ABADI',
                'alamat' => 'Gedung Office 8 Lt 8, SCBD Lot 28. Jl Jenderal Sudirman Kav 52-53, Senayan,Kebayoran Baru, Jakarta Selatan, DKI Jakarta 12190',
                'npwp' => '02.256.646.7-631.000',
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => '0.0000',
                'lost_tolerance_type' => 'percent',
                'website' => NULL,
                'term_of_payment' => 'by days',
                'top_days' => 15,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:25:59',
                'updated_at' => '2024-01-18 00:45:10',
                'type' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'code' => 'CUS-RKP-001',
                'nama' => 'PT. REA KALTIM PLANTATIONS',
                'alamat' => 'Gedung Grha Bintang 1st Floor B-C-D Jl. Jend. Sudirman No. 423 RT. 002 Damai Bahagia, Balikpapan Selatan',
                'npwp' => '01.083.701.1-725.000',
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => '0.0030',
                'lost_tolerance_type' => 'percent',
                'website' => NULL,
                'term_of_payment' => 'by days',
                'top_days' => 60,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:25:59',
                'updated_at' => '2024-04-05 11:54:00',
                'type' => 'trading',
            ),
            13 => 
            array (
                'id' => 14,
                'code' => 'CUS-SAX-001',
                'nama' => 'PT. SINGALAND ASETAMA',
                'alamat' => 'Kebun Suka Damai RT.RW. Batu Licin , Batu Licin, Tanah Bumbu',
                'npwp' => '01.585.382.3-734.000',
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => '0.0050',
                'lost_tolerance_type' => 'percent',
                'website' => NULL,
                'term_of_payment' => 'by days',
                'top_days' => 60,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:26:00',
                'updated_at' => '2024-03-19 17:47:23',
                'type' => 'trading',
            ),
            14 => 
            array (
                'id' => 15,
                'code' => 'CUS-STP-001',
                'nama' => 'PT. SURYABUMI TUNGGAL PERKASA',
                'alamat' => 'Gedung Rajawali Place, Lt. 28 Jl. HR Rasuna Said Kav. B/4, Setiabudi Jakarta Selatan, DKI Jakarta',
                'npwp' => '01.824.231.3-056.000',
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => '0.0050',
                'lost_tolerance_type' => 'percent',
                'website' => NULL,
                'term_of_payment' => 'by days',
                'top_days' => 60,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:26:02',
                'updated_at' => '2024-04-05 11:55:36',
                'type' => 'trading',
            ),
            15 => 
            array (
                'id' => 16,
                'code' => 'CUS-KMB-001',
                'nama' => 'KOP MITRA BERSATU',
                'alamat' => '-',
                'npwp' => NULL,
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => NULL,
                'lost_tolerance_type' => NULL,
                'website' => NULL,
                'term_of_payment' => 'cash',
                'top_days' => 0,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:26:04',
                'updated_at' => '2023-10-16 19:08:33',
                'type' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'code' => 'CUS-TS-001',
                'nama' => 'PT. TOSSA  SHAKTI',
                'alamat' => '-',
                'npwp' => NULL,
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => NULL,
                'lost_tolerance_type' => NULL,
                'website' => NULL,
                'term_of_payment' => 'cash',
                'top_days' => 0,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:26:04',
                'updated_at' => '2023-10-16 19:08:02',
                'type' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'code' => 'CUS-MTK-001',
                'nama' => 'PT MITRA TERMINAL KALTIM',
                'alamat' => '-',
                'npwp' => NULL,
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => NULL,
                'lost_tolerance_type' => NULL,
                'website' => NULL,
                'term_of_payment' => 'cash',
                'top_days' => 0,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:26:04',
                'updated_at' => '2023-10-16 19:07:25',
                'type' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'code' => 'CUS-AMM-001',
                'nama' => 'PT. ANTAREJA MAHADA MAKMUR',
                'alamat' => '-',
                'npwp' => '84.129.824.3-012.000',
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => '0.0000',
                'lost_tolerance_type' => NULL,
                'website' => NULL,
                'term_of_payment' => 'cash',
                'top_days' => 0,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:26:04',
                'updated_at' => '2023-10-17 20:55:32',
                'type' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'code' => 'CUS-AEK-001',
                'nama' => 'PT. ANUGRAH ENERGI KALIMANTAN',
                'alamat' => '-',
                'npwp' => NULL,
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => NULL,
                'lost_tolerance_type' => NULL,
                'website' => NULL,
                'term_of_payment' => 'cash',
                'top_days' => 0,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:26:04',
                'updated_at' => '2023-10-16 19:06:21',
                'type' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'code' => 'CUS-PSX-0002',
                'nama' => 'PT. PETROPRIMA SEJAHTERA',
                'alamat' => '-',
                'npwp' => NULL,
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => NULL,
                'lost_tolerance_type' => NULL,
                'website' => NULL,
                'term_of_payment' => 'cash',
                'top_days' => 0,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:26:04',
                'updated_at' => '2023-10-16 19:05:57',
                'type' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'code' => 'CUS-BBL-001',
                'nama' => 'CV. BUANA BARA LESTARI',
                'alamat' => '-',
                'npwp' => NULL,
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => NULL,
                'lost_tolerance_type' => NULL,
                'website' => NULL,
                'term_of_payment' => 'cash',
                'top_days' => 0,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:26:05',
                'updated_at' => '2023-10-16 19:01:34',
                'type' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'code' => 'CUS-JSL-001',
                'nama' => 'JOYLINK SHIPPING LTD',
                'alamat' => '-',
                'npwp' => NULL,
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => NULL,
                'lost_tolerance_type' => NULL,
                'website' => NULL,
                'term_of_payment' => 'cash',
                'top_days' => 0,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:26:05',
                'updated_at' => '2023-10-16 19:01:57',
                'type' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'code' => 'CUS-BF-001',
                'nama' => 'PT BRIDGE FORTUNE ',
                'alamat' => '-',
                'npwp' => NULL,
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => NULL,
                'lost_tolerance_type' => NULL,
                'website' => NULL,
                'term_of_payment' => 'cash',
                'top_days' => 0,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:26:05',
                'updated_at' => '2023-10-16 19:02:21',
                'type' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'code' => 'CUS-LPG-001',
                'nama' => 'PT LANGGENG PRIMA GASINDO',
                'alamat' => '-',
                'npwp' => NULL,
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => NULL,
                'lost_tolerance_type' => NULL,
                'website' => NULL,
                'term_of_payment' => 'cash',
                'top_days' => 0,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:26:05',
                'updated_at' => '2023-10-16 19:02:46',
                'type' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'code' => 'CUS-SPU-001',
                'nama' => 'PT SINAR PETROBIMA UTAMA',
                'alamat' => '-',
                'npwp' => NULL,
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => NULL,
                'lost_tolerance_type' => NULL,
                'website' => NULL,
                'term_of_payment' => 'cash',
                'top_days' => 0,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:26:05',
                'updated_at' => '2023-10-16 19:04:40',
                'type' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'code' => 'CUS-BAN-001',
                'nama' => 'PT. BAHTERA ANUGRAH NARWASTU',
                'alamat' => '-',
                'npwp' => NULL,
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => NULL,
                'lost_tolerance_type' => NULL,
                'website' => NULL,
                'term_of_payment' => 'cash',
                'top_days' => 0,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:26:05',
                'updated_at' => '2023-10-16 19:03:13',
                'type' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'code' => 'CUS-BSL-001',
                'nama' => 'PT. BARUNA SHIPPING LINES',
                'alamat' => '-',
                'npwp' => NULL,
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => NULL,
                'lost_tolerance_type' => NULL,
                'website' => NULL,
                'term_of_payment' => 'cash',
                'top_days' => 0,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:26:05',
                'updated_at' => '2023-10-16 19:03:46',
                'type' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'code' => 'CUS-BPX-001',
                'nama' => 'PT. BENGKULU PERMAI',
                'alamat' => '-',
                'npwp' => NULL,
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => NULL,
                'lost_tolerance_type' => NULL,
                'website' => NULL,
                'term_of_payment' => 'cash',
                'top_days' => 0,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:26:05',
                'updated_at' => '2023-10-16 19:04:14',
                'type' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'code' => 'CUS-BAS-001',
                'nama' => 'PT. BORNEO ANUGRAH SEJAHTERA',
                'alamat' => '-',
                'npwp' => NULL,
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => NULL,
                'lost_tolerance_type' => NULL,
                'website' => NULL,
                'term_of_payment' => 'cash',
                'top_days' => 0,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:26:06',
                'updated_at' => '2023-10-16 18:59:47',
                'type' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'code' => 'CUS-HEP-001',
                'nama' => 'PT. HOFFMEN ENERGI PERKASA',
                'alamat' => '-',
                'npwp' => NULL,
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => NULL,
                'lost_tolerance_type' => NULL,
                'website' => NULL,
                'term_of_payment' => 'cash',
                'top_days' => 0,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:26:06',
                'updated_at' => '2023-10-16 19:00:12',
                'type' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'code' => 'CUS-IPX-001',
                'nama' => 'PT. INDAH PRATIWI',
                'alamat' => '-',
                'npwp' => NULL,
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => NULL,
                'lost_tolerance_type' => NULL,
                'website' => NULL,
                'term_of_payment' => 'cash',
                'top_days' => 0,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:26:06',
                'updated_at' => '2023-10-16 19:41:32',
                'type' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'code' => 'CUS-ILS-001',
                'nama' => 'PT. INTI LINGGA SEJAHTERA',
                'alamat' => '-',
                'npwp' => NULL,
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => NULL,
                'lost_tolerance_type' => NULL,
                'website' => NULL,
                'term_of_payment' => 'cash',
                'top_days' => 0,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:26:06',
                'updated_at' => '2023-10-16 19:00:39',
                'type' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'code' => 'CUS-JMK-001',
                'nama' => 'PT. JAGAD MAHESA KARYA',
                'alamat' => '-',
                'npwp' => NULL,
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => NULL,
                'lost_tolerance_type' => NULL,
                'website' => NULL,
                'term_of_payment' => 'cash',
                'top_days' => 0,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:26:06',
                'updated_at' => '2023-10-16 19:42:08',
                'type' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'code' => 'CUS-KSX-001',
                'nama' => 'PT. KALTIM SUPACOAL',
                'alamat' => '-',
                'npwp' => NULL,
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => NULL,
                'lost_tolerance_type' => NULL,
                'website' => NULL,
                'term_of_payment' => 'cash',
                'top_days' => 0,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:26:07',
                'updated_at' => '2023-10-16 18:56:44',
                'type' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'code' => 'CUS-KNX-001',
                'nama' => 'PT. KERTAS NUSANTARA',
                'alamat' => '-',
                'npwp' => NULL,
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => NULL,
                'lost_tolerance_type' => NULL,
                'website' => NULL,
                'term_of_payment' => 'cash',
                'top_days' => 0,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:26:07',
                'updated_at' => '2023-10-16 18:57:18',
                'type' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'code' => 'CUS-KJP-001',
                'nama' => 'PT. Kharisma Jaya Perkasa',
                'alamat' => '-',
                'npwp' => NULL,
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => NULL,
                'lost_tolerance_type' => NULL,
                'website' => NULL,
                'term_of_payment' => 'cash',
                'top_days' => 0,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:26:07',
                'updated_at' => '2023-10-16 18:57:54',
                'type' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'code' => 'CUS-KBS-001',
                'nama' => 'PT. KONAWE BUMI SEJAHTERA',
                'alamat' => '-',
                'npwp' => NULL,
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => NULL,
                'lost_tolerance_type' => NULL,
                'website' => NULL,
                'term_of_payment' => 'cash',
                'top_days' => 0,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:26:07',
                'updated_at' => '2023-10-16 18:58:22',
                'type' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'code' => 'CUS-LIM-001',
                'nama' => 'PT. LAMINDO INTER MULTIKON',
                'alamat' => '-',
                'npwp' => NULL,
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => NULL,
                'lost_tolerance_type' => NULL,
                'website' => NULL,
                'term_of_payment' => 'cash',
                'top_days' => 0,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:26:07',
                'updated_at' => '2023-10-16 18:56:07',
                'type' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'code' => 'CUS-MNM-001',
                'nama' => 'PT. MITRA NIAGA MULIA',
                'alamat' => '-',
                'npwp' => NULL,
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => NULL,
                'lost_tolerance_type' => NULL,
                'website' => NULL,
                'term_of_payment' => 'cash',
                'top_days' => 0,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:26:07',
                'updated_at' => '2023-10-16 18:59:20',
                'type' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'code' => 'CUS-PIX-001',
                'nama' => 'PT. PACIFIC INDONESIA',
                'alamat' => '-',
                'npwp' => NULL,
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => NULL,
                'lost_tolerance_type' => NULL,
                'website' => NULL,
                'term_of_payment' => 'cash',
                'top_days' => 0,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:26:07',
                'updated_at' => '2023-10-16 18:58:46',
                'type' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'code' => 'CUS-PAP-001',
                'nama' => 'PT. PAGAR ALAM PERKASA',
                'alamat' => '-',
                'npwp' => NULL,
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => NULL,
                'lost_tolerance_type' => NULL,
                'website' => NULL,
                'term_of_payment' => 'cash',
                'top_days' => 0,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:26:08',
                'updated_at' => '2023-10-16 18:53:43',
                'type' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'code' => 'CUS-PDL-001',
                'nama' => 'PT. Pelayaran Duta Lintas Samudra',
                'alamat' => '-',
                'npwp' => NULL,
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => NULL,
                'lost_tolerance_type' => NULL,
                'website' => NULL,
                'term_of_payment' => 'cash',
                'top_days' => 0,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:26:08',
                'updated_at' => '2023-10-16 18:55:36',
                'type' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'code' => 'CUS-PKH-001',
                'nama' => 'PT. PELAYARAN KARYA HASIL BAHARI',
                'alamat' => '-',
                'npwp' => NULL,
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => NULL,
                'lost_tolerance_type' => NULL,
                'website' => NULL,
                'term_of_payment' => 'cash',
                'top_days' => 0,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:26:08',
                'updated_at' => '2023-10-16 18:54:43',
                'type' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'code' => 'CUS-PPS-001',
                'nama' => 'PT. PELAYARAN PRIMA SAMUDERA JAYA',
                'alamat' => '-',
                'npwp' => NULL,
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => NULL,
                'lost_tolerance_type' => NULL,
                'website' => NULL,
                'term_of_payment' => 'cash',
                'top_days' => 0,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:26:08',
                'updated_at' => '2023-10-16 18:55:11',
                'type' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'code' => 'CUS-PPN-001',
                'nama' => 'PT. PERTAMINA PATRA NIAGA',
                'alamat' => '-',
                'npwp' => NULL,
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => NULL,
                'lost_tolerance_type' => NULL,
                'website' => NULL,
                'term_of_payment' => 'cash',
                'top_days' => 0,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:26:09',
                'updated_at' => '2023-10-16 18:51:37',
                'type' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'code' => 'CUS-SRM-001',
                'nama' => 'PT. SRIWIJAYA RAYA MINERAL',
                'alamat' => '-',
                'npwp' => NULL,
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => NULL,
                'lost_tolerance_type' => NULL,
                'website' => NULL,
                'term_of_payment' => 'cash',
                'top_days' => 0,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:26:09',
                'updated_at' => '2023-10-16 18:49:00',
                'type' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'code' => 'CUS-TDA-001',
                'nama' => 'PT. TERANG DUNIA AGUNG',
                'alamat' => '-',
                'npwp' => NULL,
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => NULL,
                'lost_tolerance_type' => NULL,
                'website' => NULL,
                'term_of_payment' => 'cash',
                'top_days' => 0,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:26:09',
                'updated_at' => '2023-10-16 18:52:51',
                'type' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'code' => 'CUS-TKW-001',
                'nama' => 'PT. TRI KARYA WIGUNA',
                'alamat' => '-',
                'npwp' => NULL,
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => NULL,
                'lost_tolerance_type' => NULL,
                'website' => NULL,
                'term_of_payment' => 'cash',
                'top_days' => 0,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:26:09',
                'updated_at' => '2023-10-16 18:52:11',
                'type' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'code' => 'CUS-YSP-001',
                'nama' => 'PT. YAVINDO SUMBER PERSADA',
                'alamat' => '-',
                'npwp' => NULL,
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => NULL,
                'lost_tolerance_type' => NULL,
                'website' => NULL,
                'term_of_payment' => 'cash',
                'top_days' => 0,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-18 14:26:09',
                'updated_at' => '2023-10-16 18:50:58',
                'type' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'code' => 'CUS-NXX-001',
                'nama' => 'NN',
                'alamat' => '-',
                'npwp' => NULL,
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => NULL,
                'lost_tolerance_type' => NULL,
                'website' => NULL,
                'term_of_payment' => 'cash',
                'top_days' => 0,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-09-27 05:28:54',
                'updated_at' => '2023-10-16 18:50:27',
                'type' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'code' => 'CUS-SKS-001',
                'nama' => 'PT. SURYA KALIMANTAN SEJATI',
                'alamat' => 'Gedung Sinar Mas Land Plaza Menara 2 Lt 24, Jl MH Thamrin No 51, Gondangdia, Menteng, DKI Jakarta',
                'npwp' => '02.562.479.2-036.000',
                'email' => 'silvi.jelia@dss.co.id',
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => '082111800679',
                'lost_tolerance' => '0.0030',
                'lost_tolerance_type' => 'percent',
                'website' => NULL,
                'term_of_payment' => 'by days',
                'top_days' => 30,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-10-26 17:45:24',
                'updated_at' => '2023-10-26 18:47:36',
                'type' => 'trading',
            ),
            52 => 
            array (
                'id' => 53,
                'code' => 'CUS-PMM-001',
                'nama' => 'PT. PRIMA MITRAJAYA MANDIRI',
                'alamat' => 'Gedung Graha Aktiva Lt.10 Suite 1001, JL. Hr Rasuna Said Blok X-1 Kav. 03, Kuiningan Timur, Kuningan',
                'npwp' => '02.504.354.8-058.000',
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => '0.0030',
                'lost_tolerance_type' => 'percent',
                'website' => NULL,
                'term_of_payment' => 'by days',
                'top_days' => 30,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-10-26 17:46:59',
                'updated_at' => '2023-10-26 18:49:34',
                'type' => 'trading',
            ),
            53 => 
            array (
                'id' => 54,
                'code' => 'CUS-TJA-001',
                'nama' => 'PT. TEGUH JAYAPRIMA ABADI',
                'alamat' => 'Gedung Graha Aktiva Lt.10 Suite 1001, JL. Hr Rasuna Said Blok X-1 Kav. 03, Kuiningan Timur, Kuningan',
                'npwp' => '02.504.353.0-058.000',
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => '0.0030',
                'lost_tolerance_type' => 'percent',
                'website' => NULL,
                'term_of_payment' => 'by days',
                'top_days' => 30,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-10-26 17:48:05',
                'updated_at' => '2024-04-05 11:56:00',
                'type' => 'trading',
            ),
            54 => 
            array (
                'id' => 55,
                'code' => 'CUS-PCP-001',
                'nama' => 'PT. PRIMA CITRA PERDANA',
                'alamat' => 'Gedung Menara Thamrin Lt 20 Suite 2007 Jl MH Thamrin Kav 3RT 002 RW 01Kampung Bali, Tanah Abang',
                'npwp' => '02.321.134..5-038.000',
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => '0.0050',
                'lost_tolerance_type' => 'percent',
                'website' => NULL,
                'term_of_payment' => 'by days',
                'top_days' => 30,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-10-26 17:50:32',
                'updated_at' => '2023-10-26 18:49:52',
                'type' => 'trading',
            ),
            55 => 
            array (
                'id' => 56,
                'code' => 'CUS-BKL-001',
                'nama' => 'BADAN KEAMANAN LAUT',
                'alamat' => 'Jln. Proklamasi No. 56 Pegangsaan Menteng, Jakarta, DKI Jakarta',
                'npwp' => '00.118.629.5-071.000',
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => '0.0030',
                'lost_tolerance_type' => 'percent',
                'website' => NULL,
                'term_of_payment' => 'by days',
                'top_days' => 30,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-10-26 18:12:47',
                'updated_at' => '2023-10-26 18:12:47',
                'type' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'code' => 'CUS-USI-001',
                'nama' => 'PT UNITED SHIPPING INDONESIA',
                'alamat' => 'Gondosuli no 8 Surabaya',
                'npwp' => '0',
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => '0.0000',
                'lost_tolerance_type' => 'percent',
                'website' => NULL,
                'term_of_payment' => 'by days',
                'top_days' => 30,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-11-08 00:31:28',
                'updated_at' => '2023-11-08 00:31:28',
                'type' => 'trading',
            ),
            57 => 
            array (
                'id' => 58,
                'code' => 'CUS-DPA-001',
                'nama' => 'PT. DELI PRATAMA ANGKUTAN LAUT',
                'alamat' => 'Grand ITC Permata Hijau Lt 8 Jl Letjen Soepeno Suite B No. 08, Grogol Utara Kebayoran Lama, Jakarta ',
                'npwp' => NULL,
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => '0.0000',
                'lost_tolerance_type' => 'percent',
                'website' => NULL,
                'term_of_payment' => 'by days',
                'top_days' => 7,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-11-22 23:57:52',
                'updated_at' => '2023-11-22 23:57:52',
                'type' => 'trading',
            ),
            58 => 
            array (
                'id' => 59,
                'code' => 'CUS-CAP-001',
                'nama' => 'PT. COALINDO ADHI PERKASA',
                'alamat' => 'BANK MANDIRI KCP MUARA KARANG RAYA LT1, JL MUA PLUIT PENJARINGAN KOTA ADM, JAKARTA UTARA DKI JAKARTA',
                'npwp' => '84.303.451.3-047.000',
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => '0.0050',
                'lost_tolerance_type' => 'percent',
                'website' => NULL,
                'term_of_payment' => 'by days',
                'top_days' => 30,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-11-23 00:42:45',
                'updated_at' => '2023-11-23 00:42:45',
                'type' => 'trading',
            ),
            59 => 
            array (
                'id' => 60,
                'code' => 'CUS-DSN-001',
                'nama' => 'PT. DHARMA SATYA NUSANTARA',
                'alamat' => 'Grha DSN Jalan Pulo Ayang Kav.OR 3 Kawasan Industri Pulogadung, Jatinegara, Cakung, Kota Adm. Jakarta Timur, DKI Jakarta',
                'npwp' => '01.060.268.8-054.000',
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => '0.0050',
                'lost_tolerance_type' => 'percent',
                'website' => NULL,
                'term_of_payment' => 'by days',
                'top_days' => 30,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-12-22 22:35:55',
                'updated_at' => '2024-05-13 09:38:46',
                'type' => 'trading',
            ),
            60 => 
            array (
                'id' => 61,
                'code' => 'CUS-MBL-001',
                'nama' => 'PT. MANOOR BULATN LESTARI',
                'alamat' => 'BUSINESS CENTER UNIT A1 JL. SENDAWAR RAYA NO. 000 , BARONG TONGKOK, BARONG TONGKOK, KAB. KUTAI BARAT',
                'npwp' => '02.661.163.2-725.000',
                'email' => 'rahul.bannerjee@ptmbl.com',
                'bussiness_phone' => NULL,
                'mobile_phone' => '918073651792',
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => '0.0000',
                'lost_tolerance_type' => 'percent',
                'website' => NULL,
                'term_of_payment' => 'by days',
                'top_days' => 30,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2023-12-29 19:04:01',
                'updated_at' => '2024-03-19 17:48:27',
                'type' => 'trading',
            ),
            61 => 
            array (
                'id' => 62,
                'code' => 'CUS-DIN-001',
                'nama' => 'PT. DHARMA INTISAWIT NUGRAHA',
                'alamat' => 'GRHA DSN Jalan Pulo Ayang Kawasan Industri Pulogadung, Kav.OR 3 , Jatinegara, Cakung, Kota Adm. Jakarta Timur, DKI Jakarta 13930',
                'npwp' => '01.821.268.8-058.000',
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => '0.0050',
                'lost_tolerance_type' => 'percent',
                'website' => NULL,
                'term_of_payment' => 'by days',
                'top_days' => 30,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-02-21 19:47:02',
                'updated_at' => '2024-05-13 09:35:09',
                'type' => 'trading',
            ),
            62 => 
            array (
                'id' => 63,
                'code' => 'CUS-BXX-001',
                'nama' => 'PT. Bernofarm',
                'alamat' => 'Darmokali 76, Darmo, Wonokromo, Kota Surabaya, Jawa Timur 60241',
                'npwp' => '01.140.755.8-631.000',
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => '0.0030',
                'lost_tolerance_type' => 'percent',
                'website' => NULL,
                'term_of_payment' => 'by days',
                'top_days' => 30,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-02-27 17:14:27',
                'updated_at' => '2024-02-27 17:14:27',
                'type' => 'trading',
            ),
            63 => 
            array (
                'id' => 64,
                'code' => 'CUS-MUE-001',
                'nama' => 'PT. MITRA UTAMA ENERGI',
                'alamat' => 'Komp. The Centro Town House No 17 RT 03 RW 05, Sukajadi, Batam Kota, Kota Batam, Kepualauan  Riau',
                'npwp' => '03.279.201.2-225.001',
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => '0.0000',
                'lost_tolerance_type' => 'percent',
                'website' => NULL,
                'term_of_payment' => 'by days',
                'top_days' => 7,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-03-08 18:27:10',
                'updated_at' => '2024-03-08 19:24:27',
                'type' => 'trading',
            ),
            64 => 
            array (
                'id' => 65,
                'code' => 'CUS-PSP-001',
                'nama' => 'PT. PUTRA SAMUDRA PERKASA',
                'alamat' => 'Ruko Nagoya Square blok D no 93, Sungai Jodoh, Batu Ampar, Batam',
                'npwp' => '02.983.986.7-215.000',
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => '0.0000',
                'lost_tolerance_type' => 'percent',
                'website' => NULL,
                'term_of_payment' => 'by days',
                'top_days' => 7,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-03-13 16:26:18',
                'updated_at' => '2024-03-13 16:26:18',
                'type' => 'trading',
            ),
            65 => 
            array (
                'id' => 66,
                'code' => 'CUS-SKS-0002',
                'nama' => 'PT. SAKA KENCANA SEJAHTERA',
                'alamat' => 'Gedung Rajawali Place Lt. 28 Jl. HR Rasuna Said Kav B/4 Setia Budi, Setiabudi Kota Adm. Jakarta Selatan DKI Jakarta',
                'npwp' => '01.862.080.7-063.000',
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => '0.0050',
                'lost_tolerance_type' => 'percent',
                'website' => NULL,
                'term_of_payment' => 'by days',
                'top_days' => 60,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-03-15 18:02:06',
                'updated_at' => '2024-03-15 18:02:06',
                'type' => 'trading',
            ),
            66 => 
            array (
                'id' => 67,
                'code' => 'CUS-MJX-001',
                'nama' => 'CV. MULTI JASINDO',
                'alamat' => 'SOHO Skyloft Ciputra World Surabaya, Jl. Mayjen Sungkono , Gunung Sari, Dukuh Pakis, Kota Surabaya, Jawa Timur, 60224',
                'npwp' => '43.643.868.3-618.000',
                'email' => NULL,
                'bussiness_phone' => NULL,
                'mobile_phone' => NULL,
                'fax' => NULL,
                'whatsapp_number' => NULL,
                'lost_tolerance' => '0.0000',
                'lost_tolerance_type' => NULL,
                'website' => NULL,
                'term_of_payment' => 'cash',
                'top_days' => 0,
                'is_complete' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-05 11:55:12',
                'updated_at' => '2024-04-05 12:02:26',
                'type' => 'general',
            ),
        ));
        
        
    }
}