<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class EmployeeFamilyTreesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('employee_family_trees')->delete();
        
        \DB::table('employee_family_trees')->insert(array (
            0 => 
            array (
                'id' => 3,
                'employee_id' => 133,
                'type' => 'inti',
                'relation' => 'istri/suami',
                'name' => 'Istri',
                'gender' => 'female',
                'birth_place' => 'belum',
                'birth_date' => '2023-01-01',
                'education' => 'belum',
                'last_position' => 'ibu rumah tangga',
                'last_company' => 'Swasta',
                'created_at' => '2023-09-20 18:46:16',
                'updated_at' => '2023-09-20 18:46:16',
            ),
            1 => 
            array (
                'id' => 4,
                'employee_id' => 104,
                'type' => 'besar',
                'relation' => 'ayah',
                'name' => 'Ayah',
                'gender' => 'male',
                'birth_place' => 'belum',
                'birth_date' => '2023-01-01',
                'education' => 'belum',
                'last_position' => 'belum',
                'last_company' => 'belum',
                'created_at' => '2023-09-20 18:56:27',
                'updated_at' => '2023-09-20 18:56:27',
            ),
            2 => 
            array (
                'id' => 6,
                'employee_id' => 108,
                'type' => 'inti',
                'relation' => 'istri/suami',
                'name' => 'Istri',
                'gender' => 'female',
                'birth_place' => 'belum',
                'birth_date' => '2023-01-01',
                'education' => 'belum',
                'last_position' => 'belum',
                'last_company' => 'belum',
                'created_at' => '2023-09-20 19:43:37',
                'updated_at' => '2023-09-20 19:43:37',
            ),
            3 => 
            array (
                'id' => 22,
                'employee_id' => 128,
                'type' => 'besar',
                'relation' => 'ayah',
                'name' => 'Ayah',
                'gender' => 'male',
                'birth_place' => 'belum',
                'birth_date' => '2023-01-01',
                'education' => 'belum',
                'last_position' => 'belum',
                'last_company' => 'belum',
                'created_at' => '2023-09-23 00:47:11',
                'updated_at' => '2023-09-23 00:47:11',
            ),
            4 => 
            array (
                'id' => 24,
                'employee_id' => 137,
                'type' => 'besar',
                'relation' => 'ayah',
                'name' => 'Mangandar F Lubis',
                'gender' => 'male',
                'birth_place' => 'P Siantar',
                'birth_date' => '1964-10-21',
                'education' => 'S2',
                'last_position' => 'HRD',
                'last_company' => 'Lippo Group',
                'created_at' => '2023-09-25 21:26:49',
                'updated_at' => '2023-09-25 21:26:49',
            ),
            5 => 
            array (
                'id' => 25,
                'employee_id' => 137,
                'type' => 'besar',
                'relation' => 'ibu',
                'name' => 'Christina Situngkir',
                'gender' => 'female',
                'birth_place' => 'Palangkaraya',
                'birth_date' => '1967-12-18',
                'education' => 'S1',
                'last_position' => 'ibu rumah tangga',
                'last_company' => 'belum',
                'created_at' => '2023-09-25 21:26:49',
                'updated_at' => '2023-09-25 21:26:49',
            ),
            6 => 
            array (
                'id' => 26,
                'employee_id' => 138,
                'type' => 'inti',
                'relation' => 'istri/suami',
                'name' => 'Mariana',
                'gender' => 'female',
                'birth_place' => 'Medan',
                'birth_date' => '1973-08-30',
                'education' => 'S1',
                'last_position' => 'Swasta',
                'last_company' => 'Swasta',
                'created_at' => '2023-09-25 21:50:04',
                'updated_at' => '2023-09-25 21:50:04',
            ),
            7 => 
            array (
                'id' => 29,
                'employee_id' => 112,
                'type' => 'besar',
                'relation' => 'ayah',
                'name' => 'Ayah',
                'gender' => 'male',
                'birth_place' => 'belum',
                'birth_date' => '2023-01-01',
                'education' => 'belum',
                'last_position' => 'belum',
                'last_company' => 'belum',
                'created_at' => '2023-09-29 22:52:32',
                'updated_at' => '2023-09-29 22:52:32',
            ),
            8 => 
            array (
                'id' => 52,
                'employee_id' => 57,
                'type' => 'besar',
                'relation' => 'ibu',
                'name' => 'Ibu',
                'gender' => 'female',
                'birth_place' => 'belum',
                'birth_date' => '2023-10-01',
                'education' => 'SMA',
                'last_position' => 'ibu rumah tangga',
                'last_company' => 'belum',
                'created_at' => '2023-10-05 19:21:18',
                'updated_at' => '2023-10-05 19:21:18',
            ),
            9 => 
            array (
                'id' => 57,
                'employee_id' => 119,
                'type' => 'besar',
                'relation' => 'ayah',
                'name' => 'Ayah',
                'gender' => 'male',
                'birth_place' => 'belum',
                'birth_date' => '0000-00-00',
                'education' => 'belum',
                'last_position' => 'belum',
                'last_company' => 'belum',
                'created_at' => '2023-11-27 22:47:32',
                'updated_at' => '2023-11-27 22:47:32',
            ),
            10 => 
            array (
                'id' => 62,
                'employee_id' => 37,
                'type' => 'besar',
                'relation' => 'ayah',
                'name' => 'Sulasminah',
                'gender' => 'female',
                'birth_place' => 'Cepu',
                'birth_date' => '1953-04-06',
                'education' => 'SMA',
                'last_position' => 'ibu rumah tangga',
                'last_company' => 'Tidak ada',
                'created_at' => '2023-12-02 00:40:29',
                'updated_at' => '2023-12-02 00:40:29',
            ),
            11 => 
            array (
                'id' => 84,
                'employee_id' => 145,
                'type' => 'inti',
                'relation' => 'istri/suami',
                'name' => 'Hartanti',
                'gender' => 'female',
                'birth_place' => 'Limbung',
                'birth_date' => '1987-08-05',
                'education' => 'S1',
                'last_position' => 'Pegawai Negeri Sipil',
                'last_company' => '-',
                'created_at' => '2023-12-05 20:24:34',
                'updated_at' => '2023-12-05 20:24:34',
            ),
            12 => 
            array (
                'id' => 87,
                'employee_id' => 142,
                'type' => 'besar',
                'relation' => 'ayah',
                'name' => 'Muh. Syukur',
                'gender' => 'male',
                'birth_place' => '-',
                'birth_date' => '1968-11-28',
                'education' => 'SMA',
                'last_position' => 'Purnawira TNI',
                'last_company' => '-',
                'created_at' => '2023-12-05 20:50:33',
                'updated_at' => '2023-12-05 20:50:33',
            ),
            13 => 
            array (
                'id' => 88,
                'employee_id' => 142,
                'type' => 'besar',
                'relation' => 'ibu',
                'name' => 'Haspiah',
                'gender' => 'female',
                'birth_place' => '-',
                'birth_date' => '1986-08-26',
                'education' => 'SMA',
                'last_position' => 'Mengurus Rumah Tangga',
                'last_company' => '-',
                'created_at' => '2023-12-05 20:50:33',
                'updated_at' => '2023-12-05 20:50:33',
            ),
            14 => 
            array (
                'id' => 89,
                'employee_id' => 141,
                'type' => 'inti',
                'relation' => 'istri/suami',
                'name' => 'Rusnani',
                'gender' => 'female',
                'birth_place' => 'Kuningan',
                'birth_date' => '1980-07-01',
                'education' => 'SMA',
                'last_position' => 'Karyawan Swasta',
                'last_company' => '-',
                'created_at' => '2023-12-05 20:58:25',
                'updated_at' => '2023-12-05 20:58:25',
            ),
            15 => 
            array (
                'id' => 91,
                'employee_id' => 136,
                'type' => 'inti',
                'relation' => 'istri/suami',
                'name' => 'Titin Sariani Arjingga',
                'gender' => 'female',
                'birth_place' => '-',
                'birth_date' => '1983-05-07',
                'education' => '-',
                'last_position' => '-',
                'last_company' => '-',
                'created_at' => '2023-12-05 21:23:17',
                'updated_at' => '2023-12-05 21:23:17',
            ),
            16 => 
            array (
                'id' => 92,
                'employee_id' => 56,
                'type' => 'besar',
                'relation' => 'ayah',
                'name' => 'Sawija',
                'gender' => 'male',
                'birth_place' => 'Nganjuk',
                'birth_date' => '1968-05-01',
                'education' => 'SLTA',
                'last_position' => 'Swasta',
                'last_company' => 'Swasta',
                'created_at' => '2023-12-08 17:26:19',
                'updated_at' => '2023-12-08 17:26:19',
            ),
            17 => 
            array (
                'id' => 97,
                'employee_id' => 172,
                'type' => 'inti',
                'relation' => 'istri/suami',
                'name' => 'Annisa Nur Khasanah',
                'gender' => 'female',
                'birth_place' => 'Klaten',
                'birth_date' => '1996-04-22',
                'education' => 'SMA',
                'last_position' => 'Buruh Harian Lepas',
                'last_company' => '-',
                'created_at' => '2023-12-11 18:53:09',
                'updated_at' => '2023-12-11 18:53:09',
            ),
            18 => 
            array (
                'id' => 99,
                'employee_id' => 169,
                'type' => 'besar',
                'relation' => 'ayah',
                'name' => 'Abdullah',
                'gender' => 'male',
                'birth_place' => 'Bone',
                'birth_date' => '1950-12-21',
                'education' => 'Belum Tamat SD',
                'last_position' => 'Pedagang',
                'last_company' => '-',
                'created_at' => '2023-12-11 19:12:03',
                'updated_at' => '2023-12-11 19:12:03',
            ),
            19 => 
            array (
                'id' => 100,
                'employee_id' => 169,
                'type' => 'besar',
                'relation' => 'ayah',
                'name' => 'Halimah',
                'gender' => 'female',
                'birth_place' => 'Madura',
                'birth_date' => '1962-06-13',
                'education' => 'Tidak Sekolah',
                'last_position' => 'Ibu Rumah Tangga',
                'last_company' => '-',
                'created_at' => '2023-12-11 19:12:03',
                'updated_at' => '2023-12-11 19:12:03',
            ),
            20 => 
            array (
                'id' => 101,
                'employee_id' => 167,
                'type' => 'inti',
                'relation' => 'istri/suami',
                'name' => 'Ary Utami',
                'gender' => 'female',
                'birth_place' => 'Banjarmasin',
                'birth_date' => '1978-07-17',
                'education' => 'SMA',
                'last_position' => 'Tidak Ada',
                'last_company' => '-',
                'created_at' => '2023-12-11 19:49:28',
                'updated_at' => '2023-12-11 19:49:28',
            ),
            21 => 
            array (
                'id' => 102,
                'employee_id' => 166,
                'type' => 'inti',
                'relation' => 'istri/suami',
                'name' => 'Rubaiyah',
                'gender' => 'female',
                'birth_place' => 'Gambut',
                'birth_date' => '1983-08-08',
                'education' => 'SMA',
                'last_position' => 'Mengurus Rumah Tangga',
                'last_company' => '-',
                'created_at' => '2023-12-11 19:53:00',
                'updated_at' => '2023-12-11 19:53:00',
            ),
            22 => 
            array (
                'id' => 103,
                'employee_id' => 162,
                'type' => 'inti',
                'relation' => 'istri/suami',
                'name' => 'Yayan Yuniar',
                'gender' => 'female',
                'birth_place' => '-',
                'birth_date' => '1994-01-28',
                'education' => 'SMA',
                'last_position' => '-',
                'last_company' => '-',
                'created_at' => '2023-12-11 20:41:20',
                'updated_at' => '2023-12-11 20:41:20',
            ),
            23 => 
            array (
                'id' => 107,
                'employee_id' => 155,
                'type' => 'besar',
                'relation' => 'ayah',
                'name' => 'Rumiati',
                'gender' => 'female',
                'birth_place' => 'Trenggalek',
                'birth_date' => '1980-06-07',
                'education' => 'SMA',
                'last_position' => 'Karyawan Swasta',
                'last_company' => '-',
                'created_at' => '2023-12-11 21:15:31',
                'updated_at' => '2023-12-11 21:15:31',
            ),
            24 => 
            array (
                'id' => 108,
                'employee_id' => 154,
                'type' => 'besar',
                'relation' => 'ayah',
                'name' => 'Muh. Adil',
                'gender' => 'male',
                'birth_place' => 'Bira',
                'birth_date' => '1957-11-09',
                'education' => 'SD',
                'last_position' => 'Wiraswasta',
                'last_company' => '-',
                'created_at' => '2023-12-11 22:06:26',
                'updated_at' => '2023-12-11 22:06:26',
            ),
            25 => 
            array (
                'id' => 109,
                'employee_id' => 154,
                'type' => 'besar',
                'relation' => 'ayah',
                'name' => 'St. Ramlah',
                'gender' => 'female',
                'birth_place' => 'Bira',
                'birth_date' => '1963-05-10',
                'education' => 'SD',
                'last_position' => 'Mengurus Rumah Tangga',
                'last_company' => '-',
                'created_at' => '2023-12-11 22:06:26',
                'updated_at' => '2023-12-11 22:06:26',
            ),
            26 => 
            array (
                'id' => 110,
                'employee_id' => 152,
                'type' => 'besar',
                'relation' => 'ayah',
                'name' => 'Johari',
                'gender' => 'male',
                'birth_place' => 'Pare-Pare',
                'birth_date' => '1970-02-01',
                'education' => 'SD',
                'last_position' => 'Nelayan Perikanan',
                'last_company' => '-',
                'created_at' => '2023-12-11 22:12:03',
                'updated_at' => '2023-12-11 22:12:03',
            ),
            27 => 
            array (
                'id' => 111,
                'employee_id' => 151,
                'type' => 'besar',
                'relation' => 'ayah',
                'name' => 'Abd. Latif',
                'gender' => 'male',
                'birth_place' => 'Borong',
                'birth_date' => '1975-09-19',
                'education' => 'SMA',
                'last_position' => 'Petani Pekebun',
                'last_company' => '-',
                'created_at' => '2023-12-11 22:13:43',
                'updated_at' => '2023-12-11 22:13:43',
            ),
            28 => 
            array (
                'id' => 114,
                'employee_id' => 149,
                'type' => 'inti',
                'relation' => 'istri/suami',
                'name' => 'Diana',
                'gender' => 'female',
                'birth_place' => 'Tanjung Mas',
                'birth_date' => '1996-11-12',
                'education' => 'SD',
                'last_position' => 'Mengurus Rumah Tangga',
                'last_company' => '-',
                'created_at' => '2023-12-11 22:44:50',
                'updated_at' => '2023-12-11 22:44:50',
            ),
            29 => 
            array (
                'id' => 117,
                'employee_id' => 144,
                'type' => 'inti',
                'relation' => 'istri/suami',
                'name' => 'Nurmiati',
                'gender' => 'female',
                'birth_place' => 'Masamba',
                'birth_date' => '1999-12-12',
                'education' => 'S1',
                'last_position' => 'Mengurus Rumah Tangga',
                'last_company' => '-',
                'created_at' => '2023-12-11 23:17:28',
                'updated_at' => '2023-12-11 23:17:28',
            ),
            30 => 
            array (
                'id' => 118,
                'employee_id' => 12,
                'type' => 'inti',
                'relation' => 'istri/suami',
                'name' => 'Chandra Saputra',
                'gender' => 'male',
                'birth_place' => 'Pasuruan',
                'birth_date' => '1983-06-24',
                'education' => 'SMA',
                'last_position' => 'Wiraswasta',
                'last_company' => 'Wiraswasta',
                'created_at' => '2023-12-18 16:50:11',
                'updated_at' => '2023-12-18 16:50:11',
            ),
            31 => 
            array (
                'id' => 119,
                'employee_id' => 177,
                'type' => 'inti',
                'relation' => 'istri/suami',
                'name' => 'Sabariyah',
                'gender' => 'female',
                'birth_place' => 'Samarinda',
                'birth_date' => '1971-06-07',
                'education' => 'SMA',
                'last_position' => 'Mengurus Rumah Tangga',
                'last_company' => '-',
                'created_at' => '2023-12-18 18:45:54',
                'updated_at' => '2023-12-18 18:45:54',
            ),
            32 => 
            array (
                'id' => 122,
                'employee_id' => 4,
                'type' => 'besar',
                'relation' => 'ayah',
                'name' => 'Mama',
                'gender' => 'female',
                'birth_place' => 'belum',
                'birth_date' => '2023-01-01',
                'education' => 'belum',
                'last_position' => 'belum',
                'last_company' => 'belum',
                'created_at' => '2023-12-18 23:53:28',
                'updated_at' => '2023-12-18 23:53:28',
            ),
            33 => 
            array (
                'id' => 126,
                'employee_id' => 14,
                'type' => 'besar',
                'relation' => 'ayah',
                'name' => 'Ayah',
                'gender' => 'male',
                'birth_place' => 'belum',
                'birth_date' => '2023-10-01',
                'education' => 'belum',
                'last_position' => 'belum',
                'last_company' => 'belum',
                'created_at' => '2023-12-19 00:34:32',
                'updated_at' => '2023-12-19 00:34:32',
            ),
            34 => 
            array (
                'id' => 127,
                'employee_id' => 18,
                'type' => 'inti',
                'relation' => 'istri/suami',
                'name' => 'Istri',
                'gender' => 'female',
                'birth_place' => 'belum',
                'birth_date' => '2023-10-01',
                'education' => 'belum',
                'last_position' => 'belum',
                'last_company' => 'belum',
                'created_at' => '2023-12-19 00:37:00',
                'updated_at' => '2023-12-19 00:37:00',
            ),
            35 => 
            array (
                'id' => 129,
                'employee_id' => 31,
                'type' => 'inti',
                'relation' => 'istri/suami',
                'name' => 'Istri',
                'gender' => 'female',
                'birth_place' => 'belum',
                'birth_date' => '2023-10-01',
                'education' => 'S1',
                'last_position' => 'ibu rumah tangga',
                'last_company' => 'belum',
                'created_at' => '2023-12-19 00:38:41',
                'updated_at' => '2023-12-19 00:38:41',
            ),
            36 => 
            array (
                'id' => 134,
                'employee_id' => 34,
                'type' => 'inti',
                'relation' => 'istri/suami',
                'name' => 'Suami',
                'gender' => 'male',
                'birth_place' => 'belum',
                'birth_date' => '2023-01-01',
                'education' => 'belum',
                'last_position' => 'belum',
                'last_company' => 'belum',
                'created_at' => '2023-12-19 00:55:22',
                'updated_at' => '2023-12-19 00:55:22',
            ),
            37 => 
            array (
                'id' => 135,
                'employee_id' => 35,
                'type' => 'besar',
                'relation' => 'ayah',
                'name' => 'Bintara, SH',
                'gender' => 'male',
                'birth_place' => 'Nganjuk',
                'birth_date' => '1965-07-20',
                'education' => 'S1',
                'last_position' => 'Pensiunan',
                'last_company' => 'Dit Polairud Polda Jatim Surabaya',
                'created_at' => '2023-12-19 00:56:14',
                'updated_at' => '2023-12-19 00:56:14',
            ),
            38 => 
            array (
                'id' => 137,
                'employee_id' => 47,
                'type' => 'besar',
                'relation' => 'ayah',
                'name' => 'Ayah',
                'gender' => 'male',
                'birth_place' => 'belum',
                'birth_date' => '2023-01-01',
                'education' => 'belum',
                'last_position' => 'belum',
                'last_company' => 'belum',
                'created_at' => '2023-12-19 00:57:46',
                'updated_at' => '2023-12-19 00:57:46',
            ),
            39 => 
            array (
                'id' => 139,
                'employee_id' => 44,
                'type' => 'inti',
                'relation' => 'istri/suami',
                'name' => 'Khoiriyah',
                'gender' => 'female',
                'birth_place' => 'Gresik',
                'birth_date' => '1973-06-20',
                'education' => 'SLTA',
                'last_position' => 'ibu rumah tangga',
                'last_company' => 'Tidak ada',
                'created_at' => '2023-12-19 00:58:52',
                'updated_at' => '2023-12-19 00:58:52',
            ),
            40 => 
            array (
                'id' => 140,
                'employee_id' => 180,
                'type' => 'besar',
                'relation' => 'ibu',
                'name' => 'MAREM',
                'gender' => 'female',
                'birth_place' => 'LAMONGAN',
                'birth_date' => '1965-08-01',
                'education' => 'SD',
                'last_position' => 'Mengurus Rumah Tangga',
                'last_company' => '-',
                'created_at' => '2023-12-20 22:57:51',
                'updated_at' => '2023-12-20 22:57:51',
            ),
            41 => 
            array (
                'id' => 142,
                'employee_id' => 6,
                'type' => 'inti',
                'relation' => 'istri/suami',
                'name' => 'Muhammad Saiful Rochim',
                'gender' => 'male',
                'birth_place' => 'Malang',
                'birth_date' => '1983-12-28',
                'education' => 'SMA',
                'last_position' => 'belum',
                'last_company' => 'belum',
                'created_at' => '2023-12-22 21:31:01',
                'updated_at' => '2023-12-22 21:31:01',
            ),
            42 => 
            array (
                'id' => 143,
                'employee_id' => 8,
                'type' => 'inti',
                'relation' => 'istri/suami',
                'name' => 'Suami',
                'gender' => 'male',
                'birth_place' => 'Surabaya',
                'birth_date' => '1991-07-02',
                'education' => 'SMA',
                'last_position' => 'pemilik',
                'last_company' => 'wiraswasta',
                'created_at' => '2023-12-22 21:51:29',
                'updated_at' => '2023-12-22 21:51:29',
            ),
            43 => 
            array (
                'id' => 144,
                'employee_id' => 36,
                'type' => 'besar',
                'relation' => 'ayah',
                'name' => 'Yongky Wonys',
                'gender' => 'male',
                'birth_place' => 'Tuban',
                'birth_date' => '1962-08-10',
                'education' => 'SMA',
                'last_position' => 'Swasta',
                'last_company' => 'Swasta',
                'created_at' => '2023-12-22 22:07:00',
                'updated_at' => '2023-12-22 22:07:00',
            ),
            44 => 
            array (
                'id' => 145,
                'employee_id' => 39,
                'type' => 'besar',
                'relation' => 'ayah',
                'name' => 'Soemardhi',
                'gender' => 'male',
                'birth_place' => 'Jember',
                'birth_date' => '1964-08-18',
                'education' => 'SMP',
                'last_position' => 'Driver',
                'last_company' => 'Swasta',
                'created_at' => '2023-12-22 22:12:02',
                'updated_at' => '2023-12-22 22:12:02',
            ),
            45 => 
            array (
                'id' => 146,
                'employee_id' => 50,
                'type' => 'inti',
                'relation' => 'istri/suami',
                'name' => 'Paijin',
                'gender' => 'male',
                'birth_place' => 'Banyuwangi',
                'birth_date' => '1994-03-15',
                'education' => 'SLTA',
                'last_position' => 'Swasta',
                'last_company' => 'Swasta',
                'created_at' => '2023-12-22 23:35:08',
                'updated_at' => '2023-12-22 23:35:08',
            ),
            46 => 
            array (
                'id' => 147,
                'employee_id' => 38,
                'type' => 'inti',
                'relation' => 'istri/suami',
                'name' => 'Angela Luciani Santosa',
                'gender' => 'female',
                'birth_place' => 'Klaten',
                'birth_date' => '1986-10-28',
                'education' => 'S1',
                'last_position' => 'belum',
                'last_company' => 'belum',
                'created_at' => '2023-12-23 16:12:03',
                'updated_at' => '2023-12-23 16:12:03',
            ),
            47 => 
            array (
                'id' => 148,
                'employee_id' => 30,
                'type' => 'inti',
                'relation' => 'anak',
                'name' => 'Abigail Eve Simbolon',
                'gender' => 'female',
                'birth_place' => 'Sidoarjo',
                'birth_date' => '1997-12-24',
                'education' => 'S1',
                'last_position' => 'Swasta',
                'last_company' => 'Swasta',
                'created_at' => '2023-12-28 17:34:13',
                'updated_at' => '2023-12-28 17:34:13',
            ),
            48 => 
            array (
                'id' => 149,
                'employee_id' => 33,
                'type' => 'inti',
                'relation' => 'istri/suami',
                'name' => 'Suratin',
                'gender' => 'female',
                'birth_place' => 'Trenggalek',
                'birth_date' => '1986-06-01',
                'education' => 'SMA',
                'last_position' => 'ibu rumah tangga',
                'last_company' => 'Tidak ada',
                'created_at' => '2023-12-31 05:04:56',
                'updated_at' => '2023-12-31 05:04:56',
            ),
            49 => 
            array (
                'id' => 150,
                'employee_id' => 160,
                'type' => 'inti',
                'relation' => 'istri/suami',
                'name' => 'Adriella Redi P',
                'gender' => 'female',
                'birth_place' => '-',
                'birth_date' => '1987-09-24',
                'education' => '-',
                'last_position' => '-',
                'last_company' => '-',
                'created_at' => '2024-01-02 18:46:28',
                'updated_at' => '2024-01-02 18:46:28',
            ),
            50 => 
            array (
                'id' => 153,
                'employee_id' => 150,
                'type' => 'besar',
                'relation' => 'ayah',
                'name' => 'Nurdin',
                'gender' => 'male',
                'birth_place' => 'Masamba',
                'birth_date' => '1953-12-31',
                'education' => 'SD',
                'last_position' => 'Petani Pekebun',
                'last_company' => '-',
                'created_at' => '2024-01-02 18:51:22',
                'updated_at' => '2024-01-02 18:51:22',
            ),
            51 => 
            array (
                'id' => 154,
                'employee_id' => 150,
                'type' => 'besar',
                'relation' => 'ayah',
                'name' => 'Marwati',
                'gender' => 'female',
                'birth_place' => 'Masamba',
                'birth_date' => '1955-12-31',
                'education' => 'SD',
                'last_position' => 'Mengurus Rumah Tangga',
                'last_company' => '-',
                'created_at' => '2024-01-02 18:51:22',
                'updated_at' => '2024-01-02 18:51:22',
            ),
            52 => 
            array (
                'id' => 155,
                'employee_id' => 45,
                'type' => 'inti',
                'relation' => 'istri/suami',
                'name' => 'Choiril Yuniansyah',
                'gender' => 'male',
                'birth_place' => 'Surabaya',
                'birth_date' => '1993-06-27',
                'education' => 'S1',
                'last_position' => 'Swasta',
                'last_company' => 'Swasta',
                'created_at' => '2024-01-02 21:00:20',
                'updated_at' => '2024-01-02 21:00:20',
            ),
            53 => 
            array (
                'id' => 156,
                'employee_id' => 184,
                'type' => 'inti',
                'relation' => 'istri/suami',
                'name' => 'Istri',
                'gender' => 'female',
                'birth_place' => 'belum',
                'birth_date' => '2023-12-01',
                'education' => 'belum',
                'last_position' => 'ibu rumah tangga',
                'last_company' => 'belum',
                'created_at' => '2024-01-03 00:01:44',
                'updated_at' => '2024-01-03 00:01:44',
            ),
            54 => 
            array (
                'id' => 157,
                'employee_id' => 187,
                'type' => 'inti',
                'relation' => 'istri/suami',
                'name' => 'Ayah',
                'gender' => 'male',
                'birth_place' => 'belum',
                'birth_date' => '2024-01-01',
                'education' => 'belum',
                'last_position' => 'belum',
                'last_company' => 'belum',
                'created_at' => '2024-01-03 22:12:39',
                'updated_at' => '2024-01-03 22:12:39',
            ),
            55 => 
            array (
                'id' => 158,
                'employee_id' => 28,
                'type' => 'inti',
                'relation' => 'istri/suami',
                'name' => 'Emy Astuti',
                'gender' => 'female',
                'birth_place' => 'Samarinda',
                'birth_date' => '1987-01-22',
                'education' => 'S1 Sarjana pendidikan',
                'last_position' => 'Staff',
                'last_company' => 'Bappeda Litbang samarinda',
                'created_at' => '2024-01-05 17:48:41',
                'updated_at' => '2024-01-05 17:48:41',
            ),
            56 => 
            array (
                'id' => 159,
                'employee_id' => 28,
                'type' => 'inti',
                'relation' => 'anak',
                'name' => 'Khiar addien Azkandra',
                'gender' => 'male',
                'birth_place' => 'Samarinda',
                'birth_date' => '2015-10-19',
                'education' => 'Sekolah dasar',
                'last_position' => 'Pelajar',
                'last_company' => 'Pelajar',
                'created_at' => '2024-01-05 17:48:41',
                'updated_at' => '2024-01-05 17:48:41',
            ),
            57 => 
            array (
                'id' => 160,
                'employee_id' => 161,
                'type' => 'besar',
                'relation' => 'ayah',
                'name' => 'Hj. Rahmatia',
                'gender' => 'female',
                'birth_place' => '-',
                'birth_date' => '1970-11-27',
                'education' => 'SD',
                'last_position' => 'Mengurus Rumah Tangga',
                'last_company' => '-',
                'created_at' => '2024-01-05 22:17:26',
                'updated_at' => '2024-01-05 22:17:26',
            ),
            58 => 
            array (
                'id' => 161,
                'employee_id' => 158,
                'type' => 'inti',
                'relation' => 'istri/suami',
                'name' => 'Rika',
                'gender' => 'female',
                'birth_place' => 'Bacukiki',
                'birth_date' => '2001-05-05',
                'education' => 'Belum Tamat SD',
                'last_position' => 'Mengurus Rumah Tangga',
                'last_company' => '-',
                'created_at' => '2024-01-08 22:18:33',
                'updated_at' => '2024-01-08 22:18:33',
            ),
            59 => 
            array (
                'id' => 178,
                'employee_id' => 40,
                'type' => 'besar',
                'relation' => 'ayah',
                'name' => 'Chalimatus Sakdiyah',
                'gender' => 'female',
                'birth_place' => 'Surabaya',
                'birth_date' => '1961-03-11',
                'education' => 'SMA',
                'last_position' => 'ibu rumah tangga',
                'last_company' => 'Tidak ada',
                'created_at' => '2024-01-09 13:26:51',
                'updated_at' => '2024-01-09 13:26:51',
            ),
            60 => 
            array (
                'id' => 180,
                'employee_id' => 157,
                'type' => 'inti',
                'relation' => 'istri/suami',
                'name' => 'Hayrunniza',
                'gender' => 'female',
                'birth_place' => 'To\'Cemba',
                'birth_date' => '1990-06-16',
                'education' => 'SMA',
                'last_position' => 'Mengurus Rumah Tangga',
                'last_company' => '-',
                'created_at' => '2024-01-09 18:39:43',
                'updated_at' => '2024-01-09 18:39:43',
            ),
            61 => 
            array (
                'id' => 182,
                'employee_id' => 191,
                'type' => 'besar',
                'relation' => 'ayah',
                'name' => 'Sudirhan',
                'gender' => 'male',
                'birth_place' => 'Bone',
                'birth_date' => '1969-11-09',
                'education' => 'Smk',
                'last_position' => 'Petani',
                'last_company' => 'Tidak ada',
                'created_at' => '2024-01-09 18:52:08',
                'updated_at' => '2024-01-09 18:52:08',
            ),
            62 => 
            array (
                'id' => 183,
                'employee_id' => 179,
                'type' => 'besar',
                'relation' => 'ayah',
                'name' => 'ABDUL RAZAK',
                'gender' => 'male',
                'birth_place' => 'ParePare',
                'birth_date' => '1976-12-28',
                'education' => 'SD',
                'last_position' => 'Nelayan',
                'last_company' => '-',
                'created_at' => '2024-01-09 19:05:25',
                'updated_at' => '2024-01-09 19:05:25',
            ),
            63 => 
            array (
                'id' => 184,
                'employee_id' => 179,
                'type' => 'besar',
                'relation' => 'ayah',
                'name' => 'SUPIANI',
                'gender' => 'female',
                'birth_place' => 'ParePare',
                'birth_date' => '1983-01-23',
                'education' => 'SMP',
                'last_position' => 'Mengurus Rumah Tangga',
                'last_company' => '-',
                'created_at' => '2024-01-09 19:05:25',
                'updated_at' => '2024-01-09 19:05:25',
            ),
            64 => 
            array (
                'id' => 187,
                'employee_id' => 116,
                'type' => 'besar',
                'relation' => 'ayah',
                'name' => 'Supriyadi',
                'gender' => 'male',
                'birth_place' => 'Gresik',
                'birth_date' => '1973-11-21',
                'education' => 'SLTP',
                'last_position' => 'Tidak ada',
                'last_company' => 'Tidak ada',
                'created_at' => '2024-01-09 23:55:52',
                'updated_at' => '2024-01-09 23:55:52',
            ),
            65 => 
            array (
                'id' => 188,
                'employee_id' => 140,
                'type' => 'inti',
                'relation' => 'istri/suami',
                'name' => 'Dewi Are Yani',
                'gender' => 'female',
                'birth_place' => 'Samarinda',
                'birth_date' => '1989-03-18',
                'education' => 'SMA',
                'last_position' => 'Mengurus Rumah Tangga',
                'last_company' => '-',
                'created_at' => '2024-01-10 00:01:51',
                'updated_at' => '2024-01-10 00:01:51',
            ),
            66 => 
            array (
                'id' => 189,
                'employee_id' => 190,
                'type' => 'besar',
                'relation' => 'ibu',
                'name' => 'Hj.Rohani',
                'gender' => 'female',
                'birth_place' => 'Soppeng',
                'birth_date' => '1969-04-20',
                'education' => 'SMP',
                'last_position' => 'Tidak ada',
                'last_company' => 'Tidak ada',
                'created_at' => '2024-01-10 00:19:45',
                'updated_at' => '2024-01-10 00:19:45',
            ),
            67 => 
            array (
                'id' => 190,
                'employee_id' => 5,
                'type' => 'inti',
                'relation' => 'istri/suami',
                'name' => 'Sancuk Hanafi',
                'gender' => 'male',
                'birth_place' => 'Surabaya',
                'birth_date' => '1984-08-11',
                'education' => 'S1',
                'last_position' => 'Sales Manager',
                'last_company' => 'PT Liqui Moly Indonesia',
                'created_at' => '2024-01-26 00:31:16',
                'updated_at' => '2024-01-26 00:31:16',
            ),
            68 => 
            array (
                'id' => 191,
                'employee_id' => 48,
                'type' => 'inti',
                'relation' => 'istri/suami',
                'name' => 'Muhammad Faizal',
                'gender' => 'male',
                'birth_place' => 'Surabaya',
                'birth_date' => '1995-04-14',
                'education' => 'SMA',
                'last_position' => 'belum',
                'last_company' => 'belum',
                'created_at' => '2024-01-26 00:49:55',
                'updated_at' => '2024-01-26 00:49:55',
            ),
            69 => 
            array (
                'id' => 192,
                'employee_id' => 49,
                'type' => 'inti',
                'relation' => 'istri/suami',
                'name' => 'Ujang Syaiful Hidayat',
                'gender' => 'male',
                'birth_place' => 'Suabaya',
                'birth_date' => '1971-03-30',
                'education' => 'S3',
                'last_position' => 'Dosen',
                'last_company' => 'Unmer',
                'created_at' => '2024-01-26 13:19:35',
                'updated_at' => '2024-01-26 13:19:35',
            ),
            70 => 
            array (
                'id' => 193,
                'employee_id' => 49,
                'type' => 'inti',
                'relation' => 'istri/suami',
                'name' => 'Vibi Arya Ramadhany',
                'gender' => 'female',
                'birth_place' => 'Surabaya',
                'birth_date' => '2005-10-23',
                'education' => 'Kuliah',
                'last_position' => 'Mahasiswa',
                'last_company' => 'Unair',
                'created_at' => '2024-01-26 13:19:35',
                'updated_at' => '2024-01-26 13:19:35',
            ),
            71 => 
            array (
                'id' => 194,
                'employee_id' => 147,
                'type' => 'besar',
                'relation' => 'ayah',
                'name' => 'Herlando Siregar',
                'gender' => 'male',
                'birth_place' => 'Pematang Siantar',
                'birth_date' => '1970-04-20',
                'education' => 'SMA',
                'last_position' => 'Wiraswasta',
                'last_company' => '-',
                'created_at' => '2024-02-17 00:24:29',
                'updated_at' => '2024-02-17 00:24:29',
            ),
            72 => 
            array (
                'id' => 195,
                'employee_id' => 147,
                'type' => 'besar',
                'relation' => 'ayah',
                'name' => 'Rohany Samosir',
                'gender' => 'female',
                'birth_place' => 'Penambean',
                'birth_date' => '1973-05-15',
                'education' => 'SMA',
                'last_position' => 'Menegurus Rumah Tangga',
                'last_company' => '-',
                'created_at' => '2024-02-17 00:24:29',
                'updated_at' => '2024-02-17 00:24:29',
            ),
            73 => 
            array (
                'id' => 196,
                'employee_id' => 170,
                'type' => 'inti',
                'relation' => 'istri/suami',
                'name' => 'Rahmawati',
                'gender' => 'female',
                'birth_place' => 'Parebalang',
                'birth_date' => '1990-12-31',
                'education' => 'SMP',
                'last_position' => 'Ibu Rumah Tangga',
                'last_company' => '-',
                'created_at' => '2024-02-17 00:26:08',
                'updated_at' => '2024-02-17 00:26:08',
            ),
            74 => 
            array (
                'id' => 197,
                'employee_id' => 100,
                'type' => 'besar',
                'relation' => 'ayah',
                'name' => 'Ayah',
                'gender' => 'male',
                'birth_place' => 'belum',
                'birth_date' => '2023-01-01',
                'education' => 'belum',
                'last_position' => 'belum',
                'last_company' => 'belum',
                'created_at' => '2024-02-17 00:27:53',
                'updated_at' => '2024-02-17 00:27:53',
            ),
            75 => 
            array (
                'id' => 198,
                'employee_id' => 197,
                'type' => 'inti',
                'relation' => 'istri/suami',
                'name' => 'IRMA',
                'gender' => 'female',
                'birth_place' => 'Sabang Subik',
                'birth_date' => '1987-03-13',
                'education' => 'SMP',
                'last_position' => 'Mengurus Rumah Tangga',
                'last_company' => '-',
                'created_at' => '2024-02-27 23:45:07',
                'updated_at' => '2024-02-27 23:45:07',
            ),
            76 => 
            array (
                'id' => 199,
                'employee_id' => 11,
                'type' => 'besar',
                'relation' => 'ayah',
                'name' => 'belum',
                'gender' => 'male',
                'birth_place' => 'belum',
                'birth_date' => '2023-10-01',
                'education' => 'belum',
                'last_position' => 'Swasta',
                'last_company' => 'Swasta',
                'created_at' => '2024-03-14 00:32:40',
                'updated_at' => '2024-03-14 00:32:40',
            ),
            77 => 
            array (
                'id' => 200,
                'employee_id' => 199,
                'type' => 'besar',
                'relation' => 'ayah',
                'name' => 'Batti',
                'gender' => 'male',
                'birth_place' => 'Akkalibatue',
                'birth_date' => '1970-07-01',
                'education' => 'SD',
                'last_position' => 'Petani',
                'last_company' => '-',
                'created_at' => '2024-03-21 16:38:40',
                'updated_at' => '2024-03-21 16:38:40',
            ),
            78 => 
            array (
                'id' => 201,
                'employee_id' => 200,
                'type' => 'besar',
                'relation' => 'ayah',
                'name' => 'JOKSANT SAMBENTHIRO',
                'gender' => 'male',
                'birth_place' => 'SANGHE TALAUD',
                'birth_date' => '1970-06-18',
                'education' => 'SMA',
                'last_position' => 'TNI',
                'last_company' => '-',
                'created_at' => '2024-04-02 17:40:12',
                'updated_at' => '2024-04-02 17:40:12',
            ),
            79 => 
            array (
                'id' => 202,
                'employee_id' => 200,
                'type' => 'besar',
                'relation' => 'ibu',
                'name' => 'ASYERFIN WATULANGKOU',
                'gender' => 'female',
                'birth_place' => 'PANIKI',
                'birth_date' => '1971-11-10',
                'education' => 'S1',
                'last_position' => 'GURU',
                'last_company' => '-',
                'created_at' => '2024-04-02 17:40:12',
                'updated_at' => '2024-04-02 17:40:12',
            ),
            80 => 
            array (
                'id' => 204,
                'employee_id' => 201,
                'type' => 'inti',
                'relation' => 'istri/suami',
                'name' => 'INDAH NORWIDAYATI',
                'gender' => 'female',
                'birth_place' => 'SLEMAN',
                'birth_date' => '1986-08-28',
                'education' => 'SMA',
                'last_position' => 'Mengurus Rumah Tangga',
                'last_company' => '-',
                'created_at' => '2024-04-02 21:18:49',
                'updated_at' => '2024-04-02 21:18:49',
            ),
        ));
        
        
    }
}