<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ModelAuthorizationsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('model_authorizations')->delete();
        
        \DB::table('model_authorizations')->insert(array (
            0 => 
            array (
                'id' => 1,
                'model_id' => 28,
                'user_id' => 138,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Menyetujui',
                'deleted_at' => NULL,
                'created_at' => '2023-09-27 20:13:48',
                'updated_at' => '2024-02-02 23:14:13',
            ),
            1 => 
            array (
                'id' => 2,
                'model_id' => 28,
                'user_id' => 139,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Menyetujui',
                'deleted_at' => NULL,
                'created_at' => '2023-09-27 20:13:48',
                'updated_at' => '2024-02-02 23:14:13',
            ),
            2 => 
            array (
                'id' => 3,
                'model_id' => 28,
                'user_id' => 143,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Menyetujui',
                'deleted_at' => NULL,
                'created_at' => '2023-09-27 20:13:48',
                'updated_at' => '2024-02-02 23:14:13',
            ),
            3 => 
            array (
                'id' => 5,
                'model_id' => 2,
                'user_id' => 138,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2023-09-27 21:19:47',
                'updated_at' => '2024-03-14 00:37:37',
            ),
            4 => 
            array (
                'id' => 7,
                'model_id' => 31,
                'user_id' => 138,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 22:14:09',
                'updated_at' => '2024-02-02 23:32:55',
            ),
            5 => 
            array (
                'id' => 8,
                'model_id' => 31,
                'user_id' => 139,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 22:14:09',
                'updated_at' => '2024-02-02 23:32:55',
            ),
            6 => 
            array (
                'id' => 9,
                'model_id' => 31,
                'user_id' => 143,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 22:14:09',
                'updated_at' => '2024-02-02 23:32:55',
            ),
            7 => 
            array (
                'id' => 10,
                'model_id' => 26,
                'user_id' => 138,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 22:25:10',
                'updated_at' => '2024-02-02 23:27:54',
            ),
            8 => 
            array (
                'id' => 11,
                'model_id' => 26,
                'user_id' => 139,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 22:25:10',
                'updated_at' => '2024-02-02 23:27:54',
            ),
            9 => 
            array (
                'id' => 12,
                'model_id' => 26,
                'user_id' => 143,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 22:25:10',
                'updated_at' => '2024-02-02 23:27:54',
            ),
            10 => 
            array (
                'id' => 14,
                'model_id' => 32,
                'user_id' => 139,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 22:29:58',
                'updated_at' => '2023-10-19 19:08:27',
            ),
            11 => 
            array (
                'id' => 25,
                'model_id' => 48,
                'user_id' => 139,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2023-10-17 21:21:58',
                'updated_at' => '2023-10-19 16:44:31',
            ),
            12 => 
            array (
                'id' => 26,
                'model_id' => 23,
                'user_id' => 139,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2023-10-17 21:25:29',
                'updated_at' => '2024-01-12 19:16:27',
            ),
            13 => 
            array (
                'id' => 28,
                'model_id' => 9,
                'user_id' => 139,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2023-10-17 21:37:55',
                'updated_at' => '2023-10-19 16:35:05',
            ),
            14 => 
            array (
                'id' => 30,
                'model_id' => 38,
                'user_id' => 139,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2023-10-17 21:39:16',
                'updated_at' => '2023-10-19 16:43:26',
            ),
            15 => 
            array (
                'id' => 31,
                'model_id' => 7,
                'user_id' => 138,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2023-10-19 17:10:00',
                'updated_at' => '2024-03-14 00:39:21',
            ),
            16 => 
            array (
                'id' => 33,
                'model_id' => 8,
                'user_id' => 138,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2023-10-19 17:13:42',
                'updated_at' => '2024-03-14 00:39:41',
            ),
            17 => 
            array (
                'id' => 35,
                'model_id' => 6,
                'user_id' => 138,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2023-10-19 17:14:37',
                'updated_at' => '2024-03-14 00:39:02',
            ),
            18 => 
            array (
                'id' => 37,
                'model_id' => 4,
                'user_id' => 138,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2023-10-19 17:15:15',
                'updated_at' => '2024-03-14 00:38:03',
            ),
            19 => 
            array (
                'id' => 39,
                'model_id' => 5,
                'user_id' => 138,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2023-10-19 17:16:15',
                'updated_at' => '2024-03-14 00:38:21',
            ),
            20 => 
            array (
                'id' => 41,
                'model_id' => 16,
                'user_id' => 138,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2023-10-19 17:17:22',
                'updated_at' => '2024-03-14 00:42:05',
            ),
            21 => 
            array (
                'id' => 43,
                'model_id' => 19,
                'user_id' => 138,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2023-10-19 17:18:20',
                'updated_at' => '2024-03-14 00:40:54',
            ),
            22 => 
            array (
                'id' => 45,
                'model_id' => 30,
                'user_id' => 138,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2023-10-19 17:19:07',
                'updated_at' => '2024-03-14 00:44:43',
            ),
            23 => 
            array (
                'id' => 47,
                'model_id' => 41,
                'user_id' => 138,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2023-10-19 17:19:59',
                'updated_at' => '2024-03-14 00:45:47',
            ),
            24 => 
            array (
                'id' => 49,
                'model_id' => 40,
                'user_id' => 138,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2023-10-19 17:21:05',
                'updated_at' => '2024-03-14 00:45:20',
            ),
            25 => 
            array (
                'id' => 59,
                'model_id' => 12,
                'user_id' => 139,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'menyetujui',
                'deleted_at' => NULL,
                'created_at' => '2023-10-20 23:27:42',
                'updated_at' => '2023-10-20 23:27:42',
            ),
            26 => 
            array (
                'id' => 60,
                'model_id' => 47,
                'user_id' => 139,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'menyetujui',
                'deleted_at' => NULL,
                'created_at' => '2023-10-30 19:13:01',
                'updated_at' => '2023-10-30 19:13:01',
            ),
            27 => 
            array (
                'id' => 62,
                'model_id' => 44,
                'user_id' => 145,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2023-11-23 21:32:41',
                'updated_at' => '2023-11-23 21:33:46',
            ),
            28 => 
            array (
                'id' => 63,
                'model_id' => 20,
                'user_id' => 145,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2023-11-27 19:40:26',
                'updated_at' => '2023-11-27 19:40:26',
            ),
            29 => 
            array (
                'id' => 64,
                'model_id' => 13,
                'user_id' => 139,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2023-11-27 19:41:38',
                'updated_at' => '2023-11-27 19:41:38',
            ),
            30 => 
            array (
                'id' => 66,
                'model_id' => 11,
                'user_id' => 1,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2023-12-08 20:40:03',
                'updated_at' => '2023-12-08 20:40:03',
            ),
            31 => 
            array (
                'id' => 67,
                'model_id' => 36,
                'user_id' => 149,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2023-12-14 23:47:16',
                'updated_at' => '2024-02-26 16:52:05',
            ),
            32 => 
            array (
                'id' => 68,
                'model_id' => 37,
                'user_id' => 149,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2023-12-14 23:48:00',
                'updated_at' => '2024-02-26 16:52:59',
            ),
            33 => 
            array (
                'id' => 70,
                'model_id' => 35,
                'user_id' => 149,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2023-12-14 23:49:28',
                'updated_at' => '2024-02-26 16:50:52',
            ),
            34 => 
            array (
                'id' => 72,
                'model_id' => 34,
                'user_id' => 149,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2023-12-15 00:47:36',
                'updated_at' => '2024-04-03 00:29:09',
            ),
            35 => 
            array (
                'id' => 74,
                'model_id' => 36,
                'user_id' => 139,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2023-12-22 00:57:40',
                'updated_at' => '2024-02-26 16:52:05',
            ),
            36 => 
            array (
                'id' => 75,
                'model_id' => 54,
                'user_id' => 139,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2023-12-22 00:58:52',
                'updated_at' => '2023-12-22 00:58:52',
            ),
            37 => 
            array (
                'id' => 76,
                'model_id' => 2,
                'user_id' => 150,
                'level' => 2,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2024-01-11 00:32:17',
                'updated_at' => '2024-03-14 00:37:37',
            ),
            38 => 
            array (
                'id' => 77,
                'model_id' => 4,
                'user_id' => 150,
                'level' => 2,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2024-01-11 00:32:53',
                'updated_at' => '2024-03-14 00:38:03',
            ),
            39 => 
            array (
                'id' => 78,
                'model_id' => 5,
                'user_id' => 150,
                'level' => 2,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2024-01-11 00:34:53',
                'updated_at' => '2024-03-14 00:38:21',
            ),
            40 => 
            array (
                'id' => 79,
                'model_id' => 6,
                'user_id' => 150,
                'level' => 2,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2024-01-11 00:35:41',
                'updated_at' => '2024-03-14 00:39:02',
            ),
            41 => 
            array (
                'id' => 80,
                'model_id' => 7,
                'user_id' => 150,
                'level' => 2,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2024-01-11 00:36:46',
                'updated_at' => '2024-03-14 00:39:21',
            ),
            42 => 
            array (
                'id' => 81,
                'model_id' => 8,
                'user_id' => 150,
                'level' => 2,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2024-01-11 00:37:26',
                'updated_at' => '2024-03-14 00:39:41',
            ),
            43 => 
            array (
                'id' => 82,
                'model_id' => 10,
                'user_id' => 150,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2024-01-11 00:38:35',
                'updated_at' => '2024-03-14 00:40:01',
            ),
            44 => 
            array (
                'id' => 83,
                'model_id' => 15,
                'user_id' => 150,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2024-01-11 00:42:28',
                'updated_at' => '2024-03-14 00:42:37',
            ),
            45 => 
            array (
                'id' => 85,
                'model_id' => 30,
                'user_id' => 150,
                'level' => 2,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2024-01-11 00:47:45',
                'updated_at' => '2024-03-14 00:44:43',
            ),
            46 => 
            array (
                'id' => 86,
                'model_id' => 52,
                'user_id' => 150,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2024-01-11 00:50:04',
                'updated_at' => '2024-03-14 00:43:19',
            ),
            47 => 
            array (
                'id' => 88,
                'model_id' => 16,
                'user_id' => 150,
                'level' => 2,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2024-01-11 01:01:41',
                'updated_at' => '2024-03-14 00:42:05',
            ),
            48 => 
            array (
                'id' => 89,
                'model_id' => 19,
                'user_id' => 150,
                'level' => 2,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2024-01-11 01:02:32',
                'updated_at' => '2024-03-14 00:40:54',
            ),
            49 => 
            array (
                'id' => 90,
                'model_id' => 24,
                'user_id' => 150,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2024-01-11 01:03:18',
                'updated_at' => '2024-03-14 00:44:17',
            ),
            50 => 
            array (
                'id' => 91,
                'model_id' => 40,
                'user_id' => 150,
                'level' => 2,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2024-01-11 01:04:41',
                'updated_at' => '2024-03-14 00:45:20',
            ),
            51 => 
            array (
                'id' => 92,
                'model_id' => 41,
                'user_id' => 150,
                'level' => 2,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2024-01-11 01:05:35',
                'updated_at' => '2024-03-14 00:45:47',
            ),
            52 => 
            array (
                'id' => 93,
                'model_id' => 55,
                'user_id' => 149,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2024-01-12 20:23:26',
                'updated_at' => '2024-02-26 16:54:14',
            ),
            53 => 
            array (
                'id' => 94,
                'model_id' => 57,
                'user_id' => 139,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2024-01-12 20:29:56',
                'updated_at' => '2024-01-12 20:29:56',
            ),
            54 => 
            array (
                'id' => 95,
                'model_id' => 56,
                'user_id' => 149,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2024-01-12 20:30:26',
                'updated_at' => '2024-02-26 16:55:13',
            ),
            55 => 
            array (
                'id' => 98,
                'model_id' => 22,
                'user_id' => 147,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2024-01-22 17:58:35',
                'updated_at' => '2024-01-22 17:58:35',
            ),
            56 => 
            array (
                'id' => 99,
                'model_id' => 22,
                'user_id' => 145,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2024-01-22 17:58:35',
                'updated_at' => '2024-01-22 17:58:35',
            ),
            57 => 
            array (
                'id' => 100,
                'model_id' => 45,
                'user_id' => 147,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2024-01-22 17:59:18',
                'updated_at' => '2024-01-22 17:59:18',
            ),
            58 => 
            array (
                'id' => 101,
                'model_id' => 45,
                'user_id' => 145,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2024-01-22 17:59:18',
                'updated_at' => '2024-01-22 17:59:18',
            ),
            59 => 
            array (
                'id' => 102,
                'model_id' => 17,
                'user_id' => 152,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2024-02-02 18:42:02',
                'updated_at' => '2024-02-02 18:42:02',
            ),
            60 => 
            array (
                'id' => 103,
                'model_id' => 18,
                'user_id' => 152,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2024-02-02 18:42:28',
                'updated_at' => '2024-02-02 18:42:28',
            ),
            61 => 
            array (
                'id' => 104,
                'model_id' => 25,
                'user_id' => 152,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2024-02-02 18:43:02',
                'updated_at' => '2024-02-02 18:43:02',
            ),
            62 => 
            array (
                'id' => 105,
                'model_id' => 29,
                'user_id' => 152,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2024-02-02 18:43:30',
                'updated_at' => '2024-02-02 18:43:30',
            ),
            63 => 
            array (
                'id' => 106,
                'model_id' => 42,
                'user_id' => 152,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2024-02-02 18:44:00',
                'updated_at' => '2024-02-02 18:44:00',
            ),
            64 => 
            array (
                'id' => 107,
                'model_id' => 53,
                'user_id' => 152,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2024-02-02 18:44:36',
                'updated_at' => '2024-02-02 18:44:36',
            ),
            65 => 
            array (
                'id' => 108,
                'model_id' => 31,
                'user_id' => 152,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2024-02-02 21:50:48',
                'updated_at' => '2024-02-02 23:32:55',
            ),
            66 => 
            array (
                'id' => 109,
                'model_id' => 11,
                'user_id' => 152,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2024-02-02 22:00:29',
                'updated_at' => '2024-02-02 22:00:29',
            ),
            67 => 
            array (
                'id' => 110,
                'model_id' => 26,
                'user_id' => 152,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2024-02-02 22:49:14',
                'updated_at' => '2024-02-02 23:27:54',
            ),
            68 => 
            array (
                'id' => 111,
                'model_id' => 28,
                'user_id' => 152,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2024-02-02 23:14:13',
                'updated_at' => '2024-02-02 23:14:13',
            ),
            69 => 
            array (
                'id' => 112,
                'model_id' => 27,
                'user_id' => 152,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2024-02-02 23:16:30',
                'updated_at' => '2024-02-02 23:16:42',
            ),
            70 => 
            array (
                'id' => 113,
                'model_id' => 46,
                'user_id' => 152,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2024-02-02 23:20:08',
                'updated_at' => '2024-02-02 23:20:08',
            ),
            71 => 
            array (
                'id' => 114,
                'model_id' => 43,
                'user_id' => 152,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2024-02-02 23:21:33',
                'updated_at' => '2024-02-02 23:21:33',
            ),
            72 => 
            array (
                'id' => 115,
                'model_id' => 49,
                'user_id' => 149,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2024-02-07 22:27:29',
                'updated_at' => '2024-02-07 22:27:29',
            ),
            73 => 
            array (
                'id' => 116,
                'model_id' => 34,
                'user_id' => 155,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2024-02-26 16:49:48',
                'updated_at' => '2024-04-03 00:29:09',
            ),
            74 => 
            array (
                'id' => 117,
                'model_id' => 35,
                'user_id' => 155,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2024-02-26 16:50:52',
                'updated_at' => '2024-02-26 16:50:52',
            ),
            75 => 
            array (
                'id' => 118,
                'model_id' => 36,
                'user_id' => 155,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2024-02-26 16:52:05',
                'updated_at' => '2024-02-26 16:52:05',
            ),
            76 => 
            array (
                'id' => 119,
                'model_id' => 37,
                'user_id' => 155,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2024-02-26 16:52:59',
                'updated_at' => '2024-02-26 16:52:59',
            ),
            77 => 
            array (
                'id' => 120,
                'model_id' => 55,
                'user_id' => 155,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2024-02-26 16:54:14',
                'updated_at' => '2024-02-26 16:54:14',
            ),
            78 => 
            array (
                'id' => 121,
                'model_id' => 56,
                'user_id' => 155,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2024-02-26 16:55:13',
                'updated_at' => '2024-02-26 16:55:13',
            ),
            79 => 
            array (
                'id' => 122,
                'model_id' => 50,
                'user_id' => 142,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2024-02-26 18:54:30',
                'updated_at' => '2024-04-18 15:16:54',
            ),
            80 => 
            array (
                'id' => 123,
                'model_id' => 51,
                'user_id' => 142,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2024-02-26 18:55:18',
                'updated_at' => '2024-03-14 00:43:52',
            ),
            81 => 
            array (
                'id' => 124,
                'model_id' => 50,
                'user_id' => 150,
                'level' => 1,
                'minimum_value' => 0.0,
                'role' => 'Mengetahui',
                'deleted_at' => NULL,
                'created_at' => '2024-04-18 15:16:54',
                'updated_at' => '2024-04-18 15:16:54',
            ),
        ));
        
        
    }
}