<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ShNumberDetailsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('sh_number_details')->delete();
        
        \DB::table('sh_number_details')->insert(array (
            0 => 
            array (
                'id' => 167,
                'sh_number_id' => 1,
                'alamat' => 'TBBM BANJARMASIN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 21:02:29',
                'updated_at' => '2023-10-17 21:02:29',
            ),
            1 => 
            array (
                'id' => 168,
                'sh_number_id' => 1,
                'alamat' => 'DS.BATU LASUNG, KEC. KELUMPANG HULU, KAB. KOTABARU, KALIMANTAN SELATAN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 21:02:29',
                'updated_at' => '2023-10-17 21:02:29',
            ),
            2 => 
            array (
                'id' => 169,
                'sh_number_id' => 2,
                'alamat' => 'TBBM BANJARMASIN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 21:03:12',
                'updated_at' => '2023-10-17 21:03:12',
            ),
            3 => 
            array (
                'id' => 170,
                'sh_number_id' => 2,
                'alamat' => 'JL. KODECO KM.37, DESA MENTAWAKAN MULYA, KEC. MANTEWE, KAB. KOTABARU, KALIMANTAN SELATAN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 21:03:12',
                'updated_at' => '2023-10-17 21:03:12',
            ),
            4 => 
            array (
                'id' => 171,
                'sh_number_id' => 3,
                'alamat' => 'TBBM SAMARINDA',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 21:03:53',
                'updated_at' => '2023-10-17 21:03:53',
            ),
            5 => 
            array (
                'id' => 172,
                'sh_number_id' => 3,
                'alamat' => 'DESA LEBAK MANTAN, KEC. MUARA WIS , KAB. KUTAI KERTANEGARA, KALIMANTAN TIMUR',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 21:03:53',
                'updated_at' => '2023-10-17 21:03:53',
            ),
            6 => 
            array (
                'id' => 173,
                'sh_number_id' => 4,
                'alamat' => 'TBBM PALARAN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 21:04:18',
                'updated_at' => '2023-10-17 21:04:18',
            ),
            7 => 
            array (
                'id' => 174,
                'sh_number_id' => 4,
                'alamat' => 'DESA LEBAK MANTAN, KEC. MUARA WIS , KAB. KUTAI KERTANEGARA, KALIMANTAN TIMUR',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 21:04:18',
                'updated_at' => '2023-10-17 21:04:18',
            ),
            8 => 
            array (
                'id' => 175,
                'sh_number_id' => 5,
                'alamat' => 'TBBM SAMARINDA',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 21:05:02',
                'updated_at' => '2023-10-17 21:05:02',
            ),
            9 => 
            array (
                'id' => 176,
                'sh_number_id' => 5,
                'alamat' => 'DESA MUARA LEKA, JL. PROVINSI NO 74 RT IV, KEC. MUARA MUNTAI, KAB. KUTAI KARTANEGARA, KALIMANTAN TIM',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 21:05:02',
                'updated_at' => '2023-10-17 21:05:02',
            ),
            10 => 
            array (
                'id' => 177,
                'sh_number_id' => 6,
                'alamat' => 'TBBM PALARAN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 21:05:32',
                'updated_at' => '2023-10-17 21:05:32',
            ),
            11 => 
            array (
                'id' => 178,
                'sh_number_id' => 6,
                'alamat' => 'DESA MUARA LEKA, JL. PROVINSI NO 74 RT IV, KEC. MUARA MUNTAI, KAB. KUTAI KARTANEGARA, KALIMANTAN TIM',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 21:05:32',
                'updated_at' => '2023-10-17 21:05:32',
            ),
            12 => 
            array (
                'id' => 179,
                'sh_number_id' => 7,
                'alamat' => 'TBBM SAMARINDA',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 21:08:20',
                'updated_at' => '2023-10-17 21:08:20',
            ),
            13 => 
            array (
                'id' => 180,
                'sh_number_id' => 7,
                'alamat' => 'DS. PRIAN JL. PROVINSI NO 74 RT IV, KEC. MUARA MUNTAI, KAB. KUTAI KARTANEGARA, KALIMANTAN TIMUR',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 21:08:20',
                'updated_at' => '2023-10-17 21:08:20',
            ),
            14 => 
            array (
                'id' => 181,
                'sh_number_id' => 8,
                'alamat' => 'TBBM PALARAN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 21:08:41',
                'updated_at' => '2023-10-17 21:08:41',
            ),
            15 => 
            array (
                'id' => 182,
                'sh_number_id' => 8,
                'alamat' => 'DS. PRIAN JL. PROVINSI NO 74 RT IV, KEC. MUARA MUNTAI, KAB. KUTAI KARTANEGARA, KALIMANTAN TIMUR',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 21:08:41',
                'updated_at' => '2023-10-17 21:08:41',
            ),
            16 => 
            array (
                'id' => 183,
                'sh_number_id' => 9,
                'alamat' => 'TBBM BANJARMASIN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 21:10:15',
                'updated_at' => '2023-10-17 21:10:15',
            ),
            17 => 
            array (
                'id' => 184,
                'sh_number_id' => 9,
                'alamat' => 'JL. PROPINSI KM.360, DS. SEI AYUH RT.2 KEC. KELUMPANG BARAT, KAB. KOTABARU, KALIMANTAN SELATAN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 21:10:15',
                'updated_at' => '2023-10-17 21:10:15',
            ),
            18 => 
            array (
                'id' => 185,
                'sh_number_id' => 10,
                'alamat' => 'TBBM BANJARMASIN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 21:14:13',
                'updated_at' => '2023-10-17 21:14:13',
            ),
            19 => 
            array (
                'id' => 186,
                'sh_number_id' => 10,
                'alamat' => 'DESA SEKANDIS RT. O5 RW.02 GUNUNG CALANG KEC. PAMUKAN SELATAN KAB. KOTABARU, KALIMANTAN SELATAN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 21:14:13',
                'updated_at' => '2023-10-17 21:14:13',
            ),
            20 => 
            array (
                'id' => 187,
                'sh_number_id' => 11,
                'alamat' => 'DEPOT JOBBER BERAU',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            21 => 
            array (
                'id' => 188,
                'sh_number_id' => 11,
                'alamat' => 'DS. SAJAU, KEC. TANJUNG PALAS TIMUR, KAB. BULUNGAN, KALIMANTAN UTARA',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            22 => 
            array (
                'id' => 189,
                'sh_number_id' => 12,
                'alamat' => 'STS BALIKPAPAN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            23 => 
            array (
                'id' => 190,
                'sh_number_id' => 12,
                'alamat' => 'DS. JEMBAYAN, LOAKULU, KUTAI KARTANEGARA, KALIMANTAN TIMUR',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            24 => 
            array (
                'id' => 191,
                'sh_number_id' => 13,
                'alamat' => 'TBBM BANJARMASIN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            25 => 
            array (
                'id' => 192,
                'sh_number_id' => 13,
                'alamat' => 'PLTU KAJUEI, DS TUMBANG KAJUEI, KEC. RUNGAN, KAB. GUNUNG MAS, KALIMANTAN TENGAH',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            26 => 
            array (
                'id' => 193,
                'sh_number_id' => 14,
                'alamat' => 'TBBM PALARAN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            27 => 
            array (
                'id' => 194,
                'sh_number_id' => 14,
                'alamat' => 'DS. LONG MESANGAT, KEC. MUARA ANCALONG, KUTAI TIMUR, KALIMANTAN TIMUR',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            28 => 
            array (
                'id' => 195,
                'sh_number_id' => 15,
                'alamat' => 'TBBM BANJARMASIN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            29 => 
            array (
                'id' => 196,
                'sh_number_id' => 15,
                'alamat' => 'PELABUHAN BENTENG, DESA SAMPANAHAN HILIR, KEC. SAMPANAHAN, KAB. KOTABARU, KALIMANTAN SELATAN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            30 => 
            array (
                'id' => 197,
                'sh_number_id' => 16,
                'alamat' => 'TBBM BANJARMASIN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            31 => 
            array (
                'id' => 198,
                'sh_number_id' => 16,
                'alamat' => 'DS. TUMBANG KAJUEI, KEC. RUNGAN, KAB. GUNUNGMAS, KALIMANTAN TENGAH',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            32 => 
            array (
                'id' => 199,
                'sh_number_id' => 17,
                'alamat' => 'TBBM BANJARMASIN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            33 => 
            array (
                'id' => 200,
                'sh_number_id' => 17,
                'alamat' => 'DESA 4 REJOWINANGUN, KARANG BINTANG, KEC. BATULICIN, KAB. TANAHBUMBU, KALIMANTAN SELATAN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            34 => 
            array (
                'id' => 201,
                'sh_number_id' => 18,
                'alamat' => 'TBBM BANJARMASIN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            35 => 
            array (
                'id' => 202,
                'sh_number_id' => 18,
                'alamat' => 'JL RAYA BATULICIN, KEL. TANAH MERAH, KEC. BATULICIN, KAB. TANAH BUMBU, KALIMANTAN SELATAN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            36 => 
            array (
                'id' => 203,
                'sh_number_id' => 19,
                'alamat' => 'TBBM PENDINGIN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            37 => 
            array (
                'id' => 204,
                'sh_number_id' => 19,
                'alamat' => 'DS. TUANA TUHA, KEC. KENOHAN, KAB. KUTAI KARTANEGARA, KALIMANTAN TIMUR',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            38 => 
            array (
                'id' => 205,
                'sh_number_id' => 20,
                'alamat' => 'TBBM PALARAN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            39 => 
            array (
                'id' => 206,
                'sh_number_id' => 20,
                'alamat' => 'KEC. KEMBANG JANGGUT, KUTAI KERTANEGARA, KALIMANTAN TIMUR',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            40 => 
            array (
                'id' => 207,
                'sh_number_id' => 21,
                'alamat' => 'TBBM PALARAN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            41 => 
            array (
                'id' => 208,
                'sh_number_id' => 21,
                'alamat' => 'DS. LAMIN TELIHAN KEC. KENOHAN, KUTAI KERTANEGARA, KALIMANTAN TIMUR',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            42 => 
            array (
                'id' => 210,
                'sh_number_id' => 22,
                'alamat' => 'TBBM PALARAN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            43 => 
            array (
                'id' => 211,
                'sh_number_id' => 22,
                'alamat' => 'JL. PROVINSI NO 74 RT. IV KEC.MUARA MUNTAI, KUTAI KERTANEGARA, KALIMANTAN TIMUR',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            44 => 
            array (
                'id' => 212,
                'sh_number_id' => 23,
                'alamat' => 'TBBM BANJARMASIN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            45 => 
            array (
                'id' => 213,
                'sh_number_id' => 23,
                'alamat' => 'DS.KAMBUYAN, KEC. HAMPANG KM.29, KAB. KOTABARU, KALIMANTAN SELATAN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            46 => 
            array (
                'id' => 214,
                'sh_number_id' => 24,
                'alamat' => 'TBBM BANJARMASIN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            47 => 
            array (
                'id' => 215,
                'sh_number_id' => 24,
                'alamat' => 'DS. REJOWINANGUN KARANG BINTANG, KEC. BATU LICIN, KAB. TANAH BUMBU, KALIMANTAN SELATAN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            48 => 
            array (
                'id' => 216,
                'sh_number_id' => 25,
                'alamat' => 'TBBM KOTABARU',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            49 => 
            array (
                'id' => 217,
                'sh_number_id' => 25,
                'alamat' => 'DS.KAMBUYAN, KEC. HAMPANG KM.29, KAB. KOTABARU, KALIMANTAN SELATAN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            50 => 
            array (
                'id' => 218,
                'sh_number_id' => 26,
                'alamat' => 'TBBM KOTABARU',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            51 => 
            array (
                'id' => 219,
                'sh_number_id' => 26,
                'alamat' => 'DS. REJOWINANGUN KARANG BINTANG, KEC. BATU LICIN, KAB. TANAH BUMBU, KALIMANTAN SELATAN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            52 => 
            array (
                'id' => 221,
                'sh_number_id' => 27,
                'alamat' => 'TBBM KOTABARU',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            53 => 
            array (
                'id' => 222,
                'sh_number_id' => 27,
                'alamat' => 'JL. PROPINSI KM.360, DS. SEI AYUH RT.2 KEC. KELUMPANG BARAT KAB. KOTABARU, KALIMANTAN SELATAN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            54 => 
            array (
                'id' => 223,
                'sh_number_id' => 28,
                'alamat' => 'TBBM KOTABARU',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            55 => 
            array (
                'id' => 224,
                'sh_number_id' => 28,
                'alamat' => 'DESA 4 REJOWINANGUN KARANG BINTANG , KEC.  BATU LICIN, KAB. TANAH BUMBU, KALIMANTAN SELATAN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            56 => 
            array (
                'id' => 225,
                'sh_number_id' => 29,
                'alamat' => 'TBBM KOTABARU',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            57 => 
            array (
                'id' => 226,
                'sh_number_id' => 29,
                'alamat' => 'JL. RAYA BATU LICIN, KEL. TANAH MERAH KEC. BATU LICIN KAB. TANAH BUMBU, KALIMANTAN SELATAN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            58 => 
            array (
                'id' => 227,
                'sh_number_id' => 30,
                'alamat' => 'TBBM BANJARMASIN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            59 => 
            array (
                'id' => 228,
                'sh_number_id' => 30,
                'alamat' => 'PELABUHAN BENTENG, DESA SAMPAHANAN HILIR, KEC. SAMPAHANAM KAB. KOTABARU, KALIMANTAN SELATAN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            60 => 
            array (
                'id' => 229,
                'sh_number_id' => 31,
                'alamat' => 'TBBM KOTABARU',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            61 => 
            array (
                'id' => 230,
                'sh_number_id' => 31,
                'alamat' => 'PELABUHAN BENTENG, DESA SAMPAHANAN HILIR, KEC. SAMPAHANAM KAB. KOTABARU, KALIMANTAN SELATAN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            62 => 
            array (
                'id' => 231,
                'sh_number_id' => 32,
                'alamat' => 'TBBM PENDINGIN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            63 => 
            array (
                'id' => 232,
                'sh_number_id' => 32,
                'alamat' => 'DS. JEMBAYAN, LOAKULU, KUTAI KARTANEGARA, KALIMANTAN TIMUR',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            64 => 
            array (
                'id' => 233,
                'sh_number_id' => 33,
                'alamat' => 'TBBM PALARAN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            65 => 
            array (
                'id' => 234,
                'sh_number_id' => 33,
                'alamat' => 'DS. JEMBAYAN, LOAKULU, KUTAI KARTANEGARA, KALIMANTAN TIMUR',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            66 => 
            array (
                'id' => 238,
                'sh_number_id' => 35,
                'alamat' => 'SAMARINDA',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            67 => 
            array (
                'id' => 240,
                'sh_number_id' => 36,
                'alamat' => 'SAMARINDA',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            68 => 
            array (
                'id' => 241,
                'sh_number_id' => 34,
                'alamat' => 'GUDANG STOCK USI',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            69 => 
            array (
                'id' => 242,
                'sh_number_id' => 34,
                'alamat' => 'TARAKAN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            70 => 
            array (
                'id' => 243,
                'sh_number_id' => 35,
                'alamat' => 'GUDANG STOCK USI',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            71 => 
            array (
                'id' => 244,
                'sh_number_id' => 36,
                'alamat' => 'GUDANG STOCK USI',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            72 => 
            array (
                'id' => 245,
                'sh_number_id' => 37,
                'alamat' => 'TBBM SAMARINDA',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            73 => 
            array (
                'id' => 246,
                'sh_number_id' => 37,
                'alamat' => 'KEC. KEMBANG JANGGUT, KUTAI KERTANEGARA, KALIMANTAN TIMUR',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            74 => 
            array (
                'id' => 247,
                'sh_number_id' => 38,
                'alamat' => 'TBBM SAMARINDA',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            75 => 
            array (
                'id' => 248,
                'sh_number_id' => 38,
                'alamat' => 'DS. SUNGAI MARIAM, KEC. ANGGANA, KAB. KUTAI KERTANEGARA, KALIMANTAN TIMUR',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            76 => 
            array (
                'id' => 249,
                'sh_number_id' => 39,
                'alamat' => 'TBBM PALARAN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            77 => 
            array (
                'id' => 250,
                'sh_number_id' => 39,
                'alamat' => 'DS. SUNGAI MARIAM, KEC. ANGGANA, KAB. KUTAI KERTANEGARA, KALIMANTAN TIMUR',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            78 => 
            array (
                'id' => 251,
                'sh_number_id' => 40,
                'alamat' => 'TBBM SAMARINDA',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            79 => 
            array (
                'id' => 252,
                'sh_number_id' => 40,
                'alamat' => 'DS. LONG MESANGAT, KEC. MUARA ANCALONG, KAB.KUTAI TIMUR, KALIMANTAN TIMUR',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            80 => 
            array (
                'id' => 253,
                'sh_number_id' => 41,
                'alamat' => 'TBBM PENDINGIN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            81 => 
            array (
                'id' => 254,
                'sh_number_id' => 41,
                'alamat' => 'DS. LONG MESANGAT, KEC. MUARA ANCALONG, KAB. KUTAI TIMUR, KALIMANTAN TIMUR',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            82 => 
            array (
                'id' => 255,
                'sh_number_id' => 42,
                'alamat' => 'TBBM PENDINGIN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            83 => 
            array (
                'id' => 256,
                'sh_number_id' => 42,
                'alamat' => 'DS. SUNGAI MARIAM, KEC. ANGGANA, KAB. KUTAI KERTANEGARA, KALIMANTAN TIMUR',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            84 => 
            array (
                'id' => 257,
                'sh_number_id' => 43,
                'alamat' => 'TBBM SAMARINDA',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            85 => 
            array (
                'id' => 258,
                'sh_number_id' => 43,
                'alamat' => 'JL. PROVINSI NO 74 RT. IV KEC.MUARA MUNTAI, KUTAI KERTANEGARA, KALIMANTAN TIMUR',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            86 => 
            array (
                'id' => 259,
                'sh_number_id' => 44,
                'alamat' => 'TBBM PENDINGIN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            87 => 
            array (
                'id' => 260,
                'sh_number_id' => 44,
                'alamat' => 'JL. PROVINSI NO 74 RT. IV KEC.MUARA MUNTAI, KUTAI KERTANEGARA, KALIMANTAN TIMUR',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            88 => 
            array (
                'id' => 261,
                'sh_number_id' => 45,
                'alamat' => 'TBBM SAMARINDA',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            89 => 
            array (
                'id' => 262,
                'sh_number_id' => 45,
                'alamat' => 'DS. LAMIN TELIHAN KEC. KENOHAN, KUTAI KERTANEGARA, KALIMANTAN TIMUR',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            90 => 
            array (
                'id' => 263,
                'sh_number_id' => 46,
                'alamat' => 'TBBM PENDINGIN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            91 => 
            array (
                'id' => 264,
                'sh_number_id' => 46,
                'alamat' => 'DS. LAMIN TELIHAN KEC. KENOHAN, KUTAI KERTANEGARA, KALIMANTAN TIMUR',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            92 => 
            array (
                'id' => 265,
                'sh_number_id' => 47,
                'alamat' => 'TBBM TARAKAN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            93 => 
            array (
                'id' => 266,
                'sh_number_id' => 47,
                'alamat' => 'RUB, PEGAT BUKUR',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            94 => 
            array (
                'id' => 267,
                'sh_number_id' => 48,
                'alamat' => 'TERMINAL PPS SAMARINDA',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            95 => 
            array (
                'id' => 268,
                'sh_number_id' => 48,
                'alamat' => 'DUSUN JEMBAYAN, LOAKULU, KUTAI KARTANEGARA, KALIMANTAN TIMUR',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            96 => 
            array (
                'id' => 269,
                'sh_number_id' => 49,
                'alamat' => 'TBBM PENDINGIN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            97 => 
            array (
                'id' => 270,
                'sh_number_id' => 49,
                'alamat' => 'DUSUN JEMBAYAN, LOAKULU, KUTAI KARTANEGARA, KALIMANTAN TIMUR',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            98 => 
            array (
                'id' => 271,
                'sh_number_id' => 50,
                'alamat' => 'TBBM ISG SURABAYA',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            99 => 
            array (
                'id' => 272,
                'sh_number_id' => 50,
                'alamat' => 'JL.RAYA KASRI 153, TAWANG REJO, PANDAAN, PASURUAN, JAWA TIMUR',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-17 22:18:48',
                'updated_at' => '2023-10-17 22:18:48',
            ),
            100 => 
            array (
                'id' => 273,
                'sh_number_id' => 51,
                'alamat' => 'TBBM BANJARMASIN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-26 17:51:32',
                'updated_at' => '2023-10-26 17:51:32',
            ),
            101 => 
            array (
                'id' => 274,
                'sh_number_id' => 51,
                'alamat' => 'DS.TUMBANG KAJUEI, KEC. RUNGAN, KAB. GUNUNGMAS, KALIMANTAN TENGAH',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-26 17:51:32',
                'updated_at' => '2023-10-26 17:51:32',
            ),
            102 => 
            array (
                'id' => 275,
                'sh_number_id' => 52,
                'alamat' => 'TBBM PENDINGIN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-26 17:53:25',
                'updated_at' => '2023-10-26 17:53:25',
            ),
            103 => 
            array (
                'id' => 276,
                'sh_number_id' => 52,
                'alamat' => 'BUMI PERMAI MILL, KOTABANGUN, KUTAI KERTANEGARA, KALIMANTAN TIMUR',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-26 17:53:25',
                'updated_at' => '2023-10-26 17:53:25',
            ),
            104 => 
            array (
                'id' => 277,
                'sh_number_id' => 53,
                'alamat' => 'TBBM PALARAN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-26 17:54:06',
                'updated_at' => '2023-10-26 17:54:06',
            ),
            105 => 
            array (
                'id' => 278,
                'sh_number_id' => 53,
                'alamat' => 'BUMI PERMAI MILL, KOTABANGUN, KUTAI KERTANEGARA, KALIMANTAN TIMUR',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-26 17:54:06',
                'updated_at' => '2023-10-26 17:54:06',
            ),
            106 => 
            array (
                'id' => 279,
                'sh_number_id' => 54,
                'alamat' => 'TBBM PENDINGIN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-26 18:02:28',
                'updated_at' => '2023-10-26 18:02:28',
            ),
            107 => 
            array (
                'id' => 280,
                'sh_number_id' => 54,
                'alamat' => 'RAHAYU MILL, MUARA KAMAN, KUTAI KARTANEGARA, KALIMANTAN TIMUR',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-26 18:02:28',
                'updated_at' => '2023-10-26 18:02:28',
            ),
            108 => 
            array (
                'id' => 281,
                'sh_number_id' => 55,
                'alamat' => 'TBBM PALARAN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-26 18:02:52',
                'updated_at' => '2023-10-26 18:02:52',
            ),
            109 => 
            array (
                'id' => 282,
                'sh_number_id' => 55,
                'alamat' => 'RAHAYU MILL, MUARA KAMAN, KUTAI KARTANEGARA, KALIMANTAN TIMUR',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-26 18:02:52',
                'updated_at' => '2023-10-26 18:02:52',
            ),
            110 => 
            array (
                'id' => 283,
                'sh_number_id' => 56,
                'alamat' => 'TBBM KOTABARU',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-26 18:04:19',
                'updated_at' => '2023-10-26 18:04:19',
            ),
            111 => 
            array (
                'id' => 284,
                'sh_number_id' => 56,
                'alamat' => 'DS.BATU LASUNG, KEC. KELUMPANG HULU, KAB. KOTABARU, KALIMANTAN SELATAN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-26 18:04:19',
                'updated_at' => '2023-10-26 18:04:19',
            ),
            112 => 
            array (
                'id' => 285,
                'sh_number_id' => 57,
                'alamat' => 'TBBM KOTABARU',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-26 18:04:39',
                'updated_at' => '2023-10-26 18:04:39',
            ),
            113 => 
            array (
                'id' => 286,
                'sh_number_id' => 57,
                'alamat' => 'JL. KODECO KM.37, DESA MENTAWAKAN MULYA, KEC. MANTEWE, KAB. KOTABARU, KALIMANTAN SELATAN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-26 18:04:39',
                'updated_at' => '2023-10-26 18:04:39',
            ),
            114 => 
            array (
                'id' => 287,
                'sh_number_id' => 58,
                'alamat' => 'TBBM PENDINGIN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-26 18:04:59',
                'updated_at' => '2023-10-26 18:04:59',
            ),
            115 => 
            array (
                'id' => 288,
                'sh_number_id' => 58,
                'alamat' => 'DS. PRIAN JL. PROVINSI NO 74 RT IV, KEC. MUNTAI, KUTAI KERTANEGARA',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-26 18:04:59',
                'updated_at' => '2023-10-26 18:04:59',
            ),
            116 => 
            array (
                'id' => 289,
                'sh_number_id' => 59,
                'alamat' => 'TBBM PENDINGIN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-26 18:05:21',
                'updated_at' => '2023-10-26 18:05:21',
            ),
            117 => 
            array (
                'id' => 290,
                'sh_number_id' => 59,
                'alamat' => 'DESA MUARA LEKA, JL. PROVINSI NO 74 RT IV, KEC. MUNTAI KERTANEGARA',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-26 18:05:21',
                'updated_at' => '2023-10-26 18:05:21',
            ),
            118 => 
            array (
                'id' => 291,
                'sh_number_id' => 60,
                'alamat' => 'TBBM PENDINGIN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-26 18:05:38',
                'updated_at' => '2023-10-26 18:05:38',
            ),
            119 => 
            array (
                'id' => 292,
                'sh_number_id' => 60,
                'alamat' => 'DESA LEBAK MANTAN, KEC. MUARA WIS , KAB. KUTAI KERTANEGARA, KALIMANTAN TIMUR',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-26 18:05:38',
                'updated_at' => '2023-10-26 18:05:38',
            ),
            120 => 
            array (
                'id' => 293,
                'sh_number_id' => 61,
                'alamat' => 'TBBM TUAL',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-26 18:17:50',
                'updated_at' => '2023-10-26 18:17:50',
            ),
            121 => 
            array (
                'id' => 294,
                'sh_number_id' => 61,
                'alamat' => 'TUAL',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-26 18:17:50',
                'updated_at' => '2023-10-26 18:17:50',
            ),
            122 => 
            array (
                'id' => 295,
                'sh_number_id' => 62,
                'alamat' => 'TBBM SORONG',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-26 18:18:41',
                'updated_at' => '2023-10-26 18:18:41',
            ),
            123 => 
            array (
                'id' => 296,
                'sh_number_id' => 62,
                'alamat' => 'FUEL TERMINAL SORONG',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-26 18:18:41',
                'updated_at' => '2023-10-26 18:18:41',
            ),
            124 => 
            array (
                'id' => 297,
                'sh_number_id' => 63,
                'alamat' => 'TBBM WAYAME',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-26 18:19:04',
                'updated_at' => '2023-10-26 18:19:04',
            ),
            125 => 
            array (
                'id' => 298,
                'sh_number_id' => 63,
                'alamat' => 'PELABUHAN BAKAMLA AMBON',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-26 18:19:04',
                'updated_at' => '2023-10-26 18:19:04',
            ),
            126 => 
            array (
                'id' => 299,
                'sh_number_id' => 64,
                'alamat' => 'TBBM TANJUNG UBAN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-26 18:19:33',
                'updated_at' => '2023-10-26 18:19:33',
            ),
            127 => 
            array (
                'id' => 300,
                'sh_number_id' => 64,
                'alamat' => 'TANJUNG UBAN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-26 18:19:33',
                'updated_at' => '2023-10-26 18:19:33',
            ),
            128 => 
            array (
                'id' => 301,
                'sh_number_id' => 65,
                'alamat' => 'TBBM BATAM',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-26 18:20:06',
                'updated_at' => '2023-10-26 18:20:06',
            ),
            129 => 
            array (
                'id' => 302,
                'sh_number_id' => 65,
                'alamat' => 'LOBAM BATAM',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-26 18:20:06',
                'updated_at' => '2023-10-26 18:20:06',
            ),
            130 => 
            array (
                'id' => 303,
                'sh_number_id' => 66,
                'alamat' => 'TBBM DUMAI',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-26 18:20:30',
                'updated_at' => '2023-10-26 18:20:30',
            ),
            131 => 
            array (
                'id' => 304,
                'sh_number_id' => 66,
                'alamat' => 'DUMAI',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-26 18:20:30',
                'updated_at' => '2023-10-26 18:20:30',
            ),
            132 => 
            array (
                'id' => 305,
                'sh_number_id' => 67,
                'alamat' => 'TBBM BELAWAN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-26 18:20:49',
                'updated_at' => '2023-10-26 18:20:49',
            ),
            133 => 
            array (
                'id' => 306,
                'sh_number_id' => 67,
                'alamat' => 'BELAWAN MEDAN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-26 18:20:49',
                'updated_at' => '2023-10-26 18:20:49',
            ),
            134 => 
            array (
                'id' => 307,
                'sh_number_id' => 68,
                'alamat' => 'TBBM PANJANG',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-26 18:21:48',
                'updated_at' => '2023-10-26 18:21:48',
            ),
            135 => 
            array (
                'id' => 308,
                'sh_number_id' => 68,
                'alamat' => 'PELABUHAN PANJANG, LAMPUNG',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-26 18:21:48',
                'updated_at' => '2023-10-26 18:21:48',
            ),
            136 => 
            array (
                'id' => 309,
                'sh_number_id' => 69,
                'alamat' => 'TBBM BANJARMASIN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-26 18:22:08',
                'updated_at' => '2023-10-26 18:22:08',
            ),
            137 => 
            array (
                'id' => 310,
                'sh_number_id' => 69,
                'alamat' => 'PERAIRAN BANJARMASIN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-26 18:22:08',
                'updated_at' => '2023-10-26 18:22:08',
            ),
            138 => 
            array (
                'id' => 311,
                'sh_number_id' => 70,
                'alamat' => 'TBBM BITUNG',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-26 18:22:27',
                'updated_at' => '2023-10-26 18:22:27',
            ),
            139 => 
            array (
                'id' => 312,
                'sh_number_id' => 70,
                'alamat' => 'MNINAHASA',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-26 18:22:27',
                'updated_at' => '2023-10-26 18:22:27',
            ),
            140 => 
            array (
                'id' => 313,
                'sh_number_id' => 71,
                'alamat' => 'TBBM KENDARI',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-26 18:22:45',
                'updated_at' => '2023-10-26 18:22:45',
            ),
            141 => 
            array (
                'id' => 314,
                'sh_number_id' => 71,
                'alamat' => 'KENDARI',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-26 18:22:45',
                'updated_at' => '2023-10-26 18:22:45',
            ),
            142 => 
            array (
                'id' => 315,
                'sh_number_id' => 72,
                'alamat' => 'TBBM MAKASSAR',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-10-26 18:23:02',
                'updated_at' => '2023-10-26 18:23:02',
            ),
            143 => 
            array (
                'id' => 316,
                'sh_number_id' => 72,
                'alamat' => 'MAKASSAR',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-10-26 18:23:02',
                'updated_at' => '2023-10-26 18:23:02',
            ),
            144 => 
            array (
                'id' => 317,
                'sh_number_id' => 73,
                'alamat' => 'Floating Storage PPS',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-11-08 00:32:35',
                'updated_at' => '2023-11-08 00:32:35',
            ),
            145 => 
            array (
                'id' => 318,
                'sh_number_id' => 73,
                'alamat' => 'Pangkalan USI LOA KULU SAMARINDA',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-11-08 00:32:35',
                'updated_at' => '2023-11-08 00:32:35',
            ),
            146 => 
            array (
                'id' => 319,
                'sh_number_id' => 74,
                'alamat' => 'AGEN JAKARTA',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-11-13 18:36:51',
                'updated_at' => '2023-11-13 18:36:51',
            ),
            147 => 
            array (
                'id' => 320,
                'sh_number_id' => 74,
                'alamat' => 'JAKARTA',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-11-13 18:36:51',
                'updated_at' => '2023-11-13 18:36:51',
            ),
            148 => 
            array (
                'id' => 321,
                'sh_number_id' => 75,
                'alamat' => 'Pangkalan USI Loa Kulu',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-11-23 16:33:45',
                'updated_at' => '2023-11-23 16:33:45',
            ),
            149 => 
            array (
                'id' => 322,
                'sh_number_id' => 75,
                'alamat' => 'IPC site Bentuas',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-11-23 16:33:45',
                'updated_at' => '2023-11-23 16:33:45',
            ),
            150 => 
            array (
                'id' => 323,
                'sh_number_id' => 76,
                'alamat' => 'Samarinda',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-11-23 16:34:54',
                'updated_at' => '2023-11-23 16:34:54',
            ),
            151 => 
            array (
                'id' => 324,
                'sh_number_id' => 76,
                'alamat' => 'Samarinda',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-11-23 16:34:54',
                'updated_at' => '2023-11-23 16:34:54',
            ),
            152 => 
            array (
                'id' => 325,
                'sh_number_id' => 77,
                'alamat' => 'Samarinda',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-11-23 16:35:35',
                'updated_at' => '2023-11-23 16:35:35',
            ),
            153 => 
            array (
                'id' => 326,
                'sh_number_id' => 77,
                'alamat' => 'IPC site Bentuas',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-11-23 16:35:35',
                'updated_at' => '2023-11-23 16:35:35',
            ),
            154 => 
            array (
                'id' => 327,
                'sh_number_id' => 78,
                'alamat' => 'SAMARINDA',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-11-23 20:32:36',
                'updated_at' => '2023-11-23 20:32:36',
            ),
            155 => 
            array (
                'id' => 328,
                'sh_number_id' => 78,
                'alamat' => 'Tenggarong Seberang, Kutai Kartanegara, Kalimantan Timur',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-11-23 20:32:36',
                'updated_at' => '2023-11-23 20:32:36',
            ),
            156 => 
            array (
                'id' => 329,
                'sh_number_id' => 79,
                'alamat' => 'TBBM JOBBER BERAU',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-12-22 22:51:59',
                'updated_at' => '2023-12-22 22:51:59',
            ),
            157 => 
            array (
                'id' => 330,
                'sh_number_id' => 79,
                'alamat' => 'DESA LABANAN, KEC. LABANAN, KAB. TANJUNG REDEB, KALIMANTAN TIMUR',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-12-22 22:51:59',
                'updated_at' => '2023-12-22 22:51:59',
            ),
            158 => 
            array (
                'id' => 331,
                'sh_number_id' => 80,
                'alamat' => 'TBBM SAMARINDA',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-12-29 19:05:52',
                'updated_at' => '2023-12-29 19:05:52',
            ),
            159 => 
            array (
                'id' => 332,
                'sh_number_id' => 80,
                'alamat' => 'DESA MANTAR, KEC. DAMAI,KUTAI BARAT, KALIMANTAN TIMUR',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-12-29 19:05:52',
                'updated_at' => '2023-12-29 19:05:52',
            ),
            160 => 
            array (
                'id' => 333,
                'sh_number_id' => 81,
                'alamat' => 'TBBM PALARAN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-12-29 19:06:25',
                'updated_at' => '2023-12-29 19:06:25',
            ),
            161 => 
            array (
                'id' => 334,
                'sh_number_id' => 81,
                'alamat' => 'DESA MANTAR, KEC. DAMAI,KUTAI BARAT, KALIMANTAN TIMUR',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-12-29 19:06:25',
                'updated_at' => '2023-12-29 19:06:25',
            ),
            162 => 
            array (
                'id' => 335,
                'sh_number_id' => 82,
                'alamat' => 'TBBM PENDINGIN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2023-12-29 19:07:21',
                'updated_at' => '2023-12-29 19:07:21',
            ),
            163 => 
            array (
                'id' => 336,
                'sh_number_id' => 82,
                'alamat' => 'DESA MANTAR, KEC. DAMAI,KUTAI BARAT, KALIMANTAN TIMUR',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2023-12-29 19:07:21',
                'updated_at' => '2023-12-29 19:07:21',
            ),
            164 => 
            array (
                'id' => 337,
                'sh_number_id' => 83,
                'alamat' => 'TBBM JOBBER BERAU',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2024-02-23 18:39:04',
                'updated_at' => '2024-02-23 18:39:04',
            ),
            165 => 
            array (
                'id' => 338,
                'sh_number_id' => 83,
                'alamat' => 'Desa Labanan , Kec. Labanan, Kab Tanjung Redeb, Kalimantan Timur',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2024-02-23 18:39:04',
                'updated_at' => '2024-02-23 18:39:04',
            ),
            166 => 
            array (
                'id' => 339,
                'sh_number_id' => 84,
                'alamat' => 'TBBM ISG SURABAYA',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2024-02-27 17:22:15',
                'updated_at' => '2024-02-27 17:22:15',
            ),
            167 => 
            array (
                'id' => 340,
                'sh_number_id' => 84,
                'alamat' => 'Jl. Gatot Subroto No  68, Banjar Kemantren KM 18 Buduran, Sidoarjo',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2024-02-27 17:22:15',
                'updated_at' => '2024-02-27 17:22:15',
            ),
            168 => 
            array (
                'id' => 341,
                'sh_number_id' => 85,
                'alamat' => 'TBBM TG UBAN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2024-03-08 19:09:33',
                'updated_at' => '2024-03-08 19:09:33',
            ),
            169 => 
            array (
                'id' => 342,
                'sh_number_id' => 85,
                'alamat' => 'PT Putra Samudra Perkasa, Batam',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2024-03-08 19:09:33',
                'updated_at' => '2024-03-08 19:09:33',
            ),
            170 => 
            array (
                'id' => 343,
                'sh_number_id' => 86,
                'alamat' => 'TBBM BATAM',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2024-03-08 19:09:56',
                'updated_at' => '2024-03-08 19:09:56',
            ),
            171 => 
            array (
                'id' => 344,
                'sh_number_id' => 86,
                'alamat' => 'PT Putra Samudra Perkasa, Batam',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2024-03-08 19:09:56',
                'updated_at' => '2024-03-08 19:09:56',
            ),
            172 => 
            array (
                'id' => 345,
                'sh_number_id' => 87,
                'alamat' => 'TBBM TANJUNG UBAN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2024-03-13 16:27:58',
                'updated_at' => '2024-03-13 16:27:58',
            ),
            173 => 
            array (
                'id' => 346,
                'sh_number_id' => 87,
                'alamat' => 'BATAM',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2024-03-13 16:27:58',
                'updated_at' => '2024-03-13 16:27:58',
            ),
            174 => 
            array (
                'id' => 347,
                'sh_number_id' => 88,
                'alamat' => 'TBBM BATAM',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2024-03-13 16:28:33',
                'updated_at' => '2024-03-13 16:28:33',
            ),
            175 => 
            array (
                'id' => 348,
                'sh_number_id' => 88,
                'alamat' => 'BATAM',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2024-03-13 16:28:33',
                'updated_at' => '2024-03-13 16:28:33',
            ),
            176 => 
            array (
                'id' => 349,
                'sh_number_id' => 89,
                'alamat' => 'TBBM BANJARMASIN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2024-03-15 19:26:08',
                'updated_at' => '2024-03-15 19:26:08',
            ),
            177 => 
            array (
                'id' => 350,
                'sh_number_id' => 89,
                'alamat' => 'DESA SEKANDIS RT. O5 RW.02 GUNUNG CALANG KEC. PAMUKAN SELATAN KAB. KOTABARU, KALIMANTAN SELATAN',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2024-03-15 19:26:08',
                'updated_at' => '2024-03-15 19:26:08',
            ),
            178 => 
            array (
                'id' => 351,
                'sh_number_id' => 90,
                'alamat' => 'GUDANG STOCK USI',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Supply Point',
                'created_at' => '2024-03-26 16:41:16',
                'updated_at' => '2024-03-26 16:41:16',
            ),
            179 => 
            array (
                'id' => 352,
                'sh_number_id' => 90,
                'alamat' => 'SAMARINDA',
                'longitude' => NULL,
                'latitude' => NULL,
                'type' => 'Drop Point',
                'created_at' => '2024-03-26 16:41:16',
                'updated_at' => '2024-03-26 16:41:16',
            ),
        ));
        
        
    }
}