<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_type' => 'employee',
                'employee_id' => NULL,
                'branch_id' => 1,
                'division_id' => NULL,
                'username' => 'super_admin',
                'name' => 'super_admin',
                'email' => 'super_admin@gmail.com',
                'email_verified_at' => '2022-12-16 09:05:36',
                'password' => '$2a$12$Gd1gn6dEhWTuh9fdisi07eXYMXR55wDrCUP1Q/WIWlfubthZjbmhm',
                'remember_token' => 'wyBwt3be1kj0RpE9kDd4etndvcCyTZbSOWrk6LAN0V4pfzkfpmIsp4SttOiM',
                'device_token' => 'eQuw0MF4osDTE6hZ0RV2br:APA91bEdiFDPHg6w1fQIXOeZ835_v89FkTUW3Az8atP-6B4bRxrJ8svA3tHEjL5qfOwPHy-wtBBVyU-KgO7grvOB4_zdwPx_xEIN2ljRO_j8TPHD4D-SAuja9ntHk3EHShk7zGQ1Oe8e',
                'deleted_at' => NULL,
                'created_at' => '2022-12-16 09:05:36',
                'updated_at' => '2024-01-05 17:45:32',
            ),
            1 => 
            array (
                'id' => 136,
                'user_type' => 'employee',
                'employee_id' => 40,
                'branch_id' => 1,
                'division_id' => 27,
                'username' => 'risma',
                'name' => 'Risma fauziyah',
                'email' => 'fauziyahrisma@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$w02cXSzvl7zgKA2WdyEIYOOpznyOXLk1IZ.CUWvJ99QPMY0j3QqeK',
                'remember_token' => 'W9cKD6UdgyCu6T071IipHEiLbVcp0Gx2iOFi0QhxrUJhth9h3CMjzusUfH3v',
                'device_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2023-09-22 19:39:52',
                'updated_at' => '2023-09-22 19:39:52',
            ),
            2 => 
            array (
                'id' => 137,
                'user_type' => 'employee',
                'employee_id' => 6,
                'branch_id' => 1,
                'division_id' => 27,
                'username' => 'YULIANTI2428',
                'name' => 'YULIANTI KUSUMANING ARUM',
                'email' => 'invoice.usi@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$ZRpo2Y4YksuvA3OY9.qh7.R1dzdmOF9fLsJxHVYimLwJ7LbzkK5ZG',
                'remember_token' => 'W2CgQV2w3OvADDunidhmZz39Gf3TuR2pl3Kkivech6plmYn3lAaIfdQCJ6XZ',
                'device_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2023-09-22 19:40:44',
                'updated_at' => '2023-09-22 19:40:44',
            ),
            3 => 
            array (
                'id' => 138,
                'user_type' => 'employee',
                'employee_id' => 34,
                'branch_id' => 1,
                'division_id' => 5,
                'username' => 'DEWI',
                'name' => 'YIP DEWI',
                'email' => 'yipdewi76@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$GbAArZcP0c0CwVIXA5dXmeSo6pgU.3u5gtGGJkgmd0dv7GmiI5YFi',
                'remember_token' => NULL,
                'device_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2023-09-22 19:49:56',
                'updated_at' => '2023-09-22 19:49:56',
            ),
            4 => 
            array (
                'id' => 139,
                'user_type' => 'employee',
                'employee_id' => 4,
                'branch_id' => 1,
                'division_id' => 27,
                'username' => 'magda@ptusi.co.id',
                'name' => 'Magdalena Meliani Nawakona',
                'email' => 'magda@ptusi.co.id',
                'email_verified_at' => NULL,
                'password' => '$2y$10$GGArTCC4iyIyXegb2u7fF.86APtNgSFj.T1O33mjoPjMm7uukw62G',
                'remember_token' => NULL,
                'device_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2023-09-22 19:50:55',
                'updated_at' => '2023-09-22 19:50:55',
            ),
            5 => 
            array (
                'id' => 140,
                'user_type' => 'employee',
                'employee_id' => 39,
                'branch_id' => 1,
                'division_id' => 5,
                'username' => 'hanief',
                'name' => 'NUR HANIEF D.R.',
                'email' => 'hanief.3cc@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$ypZx055NqOtGyACrfY/TIu7NBiZEXJeZMeHXWXNHKIyfKybLLdOKS',
                'remember_token' => 'Jcpk9X4fEr9cXdDJFUzpQQgR9P4vLst9QWqdskT1olxgZvaqoOK90YRYYHfa',
                'device_token' => 'czQubtKvNvJ85tCMqz-oJo:APA91bGOIeLPMJyc301A6-MFhCW34OfO4l0CgpYtUBfgaKfkkVgmTDGQp_edhIza2XFDkotD3YBmPn90VVQfPCmPEJelMS8y-WPGlo6zP4mMh05ueTUQDzTXVtT9UUxQ-SrYiB0ikVS0',
                'deleted_at' => NULL,
                'created_at' => '2023-09-22 19:52:23',
                'updated_at' => '2024-01-22 23:11:47',
            ),
            6 => 
            array (
                'id' => 141,
                'user_type' => 'employee',
                'employee_id' => 7,
                'branch_id' => 1,
                'division_id' => 20,
                'username' => 'Indra WS',
                'name' => 'indrawati sutanto',
                'email' => 'sutantoindrawati@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$ivumt6p5hJABKYkV3KUlNukYLh4nBf8nmmTEbhxKEflNzHN/Uqn1C',
                'remember_token' => 'XkwkBsogFcPnyLHtS2UtuLkw4QNsdfGedwrCcRIKcVqXmZEiL8GHiH7AUOxN',
                'device_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2023-09-22 19:53:21',
                'updated_at' => '2023-09-22 19:53:21',
            ),
            7 => 
            array (
                'id' => 142,
                'user_type' => 'employee',
                'employee_id' => 8,
                'branch_id' => 1,
                'division_id' => 20,
                'username' => 'cindyfeb',
                'name' => 'Cindy Febriana Sutanto',
                'email' => 'cindy.febriana96@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$xy1rehdojFZjIRxX8zTqJudA8pLBHZU/8FbPstU0baREFvO1RArWy',
                'remember_token' => 'pKkvAQiZbejXxYSwcgnbbt82I0bCjFaKjIaNqkcpNz947gZeUeuiUVGJ2sM8',
                'device_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2023-09-22 19:56:17',
                'updated_at' => '2023-09-22 19:56:17',
            ),
            8 => 
            array (
                'id' => 143,
                'user_type' => 'employee',
                'employee_id' => 11,
                'branch_id' => 1,
                'division_id' => 20,
                'username' => 'INDRI',
                'name' => 'INDRIATI',
                'email' => 'iin.cahyadi@yahoo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$uGqVwU2VqW8/NxU0d6uocuf3OhwVVR589rho2qE0W6vKC9bnlj57K',
                'remember_token' => NULL,
                'device_token' => NULL,
                'deleted_at' => '2024-02-26 16:26:14',
                'created_at' => '2023-09-22 23:24:20',
                'updated_at' => '2024-02-26 16:26:14',
            ),
            9 => 
            array (
                'id' => 144,
                'user_type' => 'employee',
                'employee_id' => 5,
                'branch_id' => 1,
                'division_id' => 3,
                'username' => 'Evvy',
                'name' => 'Evvy Liansyah',
                'email' => 'evvyliansyah29@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$KcupTEx/S/shWAWBOu5NVuDRJTzH8/Drqtbq7AFHTPp8y3U51oI5i',
                'remember_token' => '8PA7UkFtTkXgEJoCLvXWCV8RUw4sr0fsBSWnrPrNWji6uSLA7wF3oI8AYOeg',
                'device_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2023-09-22 23:25:42',
                'updated_at' => '2023-12-16 00:39:47',
            ),
            10 => 
            array (
                'id' => 145,
                'user_type' => 'employee',
                'employee_id' => 38,
                'branch_id' => 1,
                'division_id' => 27,
                'username' => 'nicousi',
                'name' => 'Nico Yonathan',
                'email' => 'nico.yonathan@ptusi.co.id',
                'email_verified_at' => NULL,
                'password' => '$2y$10$.aDByZykL0q8r0IfpZBDj.JvPHg9sSHgIEFpe6ZfnwU5Mpm3vJj8e',
                'remember_token' => 'njCPJ2iL7cBQIvLvicyaE75w1XLNN8qXfRcrNHvvUtUgoL264GD7gywFX83U',
                'device_token' => 'cLgAMyk91zKkvX0Cul_Ww9:APA91bHogHoaJhMFS-vmUle6fwS7cO7kahgLoe1kX348DIJ6jmDxvxEJA5SLRbzQi_iPZIeAK9LVW6K_Aex-4sC5nCQH0jJzkzNuHBDDUY_RvO5UK_gyjl_UozdATHzURsGWl6eu8ZUA',
                'deleted_at' => NULL,
                'created_at' => '2023-09-22 23:26:29',
                'updated_at' => '2024-03-01 19:07:23',
            ),
            11 => 
            array (
                'id' => 146,
                'user_type' => 'employee',
                'employee_id' => 137,
                'branch_id' => 1,
                'division_id' => 3,
                'username' => 'terznta_',
                'name' => 'Ester Nasanta',
                'email' => 'esternasantaa@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$FRNzwVgH.mBh9zWkd7OYuOcSfzOtiLobYMc.F5Y2/IbZTGNlaX6t6',
                'remember_token' => 'IAe26YxhY5Nx3RE9Sjlp3zDW2pw6ywAvmSb5y0VIbgq9fsGa0lMTIRtP4e2r',
                'device_token' => 'f93KeiPL8135rwIjaSbiIc:APA91bHgpTgVu2eearPeDcdWxMfIcjmQ4GltPiGq56LB2cP4ejqFsDjY1erLjnMoV34Io9_pHZ98JnjZYg7Uu2Co8XX9B8l7jOwt-ZAM3AbS6vb6c06sghoje2ui_7dzTgdEMdpsyjXR',
                'deleted_at' => NULL,
                'created_at' => '2023-09-25 21:34:15',
                'updated_at' => '2023-10-23 16:37:39',
            ),
            12 => 
            array (
                'id' => 147,
                'user_type' => 'employee',
                'employee_id' => 159,
                'branch_id' => 1,
                'division_id' => 30,
                'username' => 'Kimberly',
                'name' => 'Kimberly Kwandy',
                'email' => 'kimberly.kwandy@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$UQPraZlpXyHpheghfUAP0.fRjETRchaff7j520mZyIqoF.b3.Uigm',
                'remember_token' => NULL,
                'device_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2023-11-28 17:18:42',
                'updated_at' => '2023-11-29 19:50:24',
            ),
            13 => 
            array (
                'id' => 148,
                'user_type' => 'employee',
                'employee_id' => 47,
                'branch_id' => 1,
                'division_id' => 4,
                'username' => 'Melany',
                'name' => 'Melany',
                'email' => 'melanyfitriana08@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$/oHdqr1kUVcGfN54XAKcS.Fji7YUqH.oio3LrtVaE8CzpBM3I.bu6',
                'remember_token' => NULL,
                'device_token' => 'czQubtKvNvJ85tCMqz-oJo:APA91bGOIeLPMJyc301A6-MFhCW34OfO4l0CgpYtUBfgaKfkkVgmTDGQp_edhIza2XFDkotD3YBmPn90VVQfPCmPEJelMS8y-WPGlo6zP4mMh05ueTUQDzTXVtT9UUxQ-SrYiB0ikVS0',
                'deleted_at' => NULL,
                'created_at' => '2023-12-07 22:12:38',
                'updated_at' => '2024-01-11 16:10:56',
            ),
            14 => 
            array (
                'id' => 149,
                'user_type' => 'employee',
                'employee_id' => 49,
                'branch_id' => 1,
                'division_id' => 4,
                'username' => 'Yani',
                'name' => 'Yani',
                'email' => 'yani.aryani05@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$/.A4MJzgHPhinz8ZSr5xL.GjQ7YyhyA5tCT322Hr02glu/p1xSLa2',
                'remember_token' => NULL,
                'device_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2023-12-07 22:20:32',
                'updated_at' => '2023-12-07 22:20:32',
            ),
            15 => 
            array (
                'id' => 150,
                'user_type' => 'employee',
                'employee_id' => 182,
                'branch_id' => 1,
                'division_id' => 20,
                'username' => 'Herry Susanto',
                'name' => 'Herry Susanto',
                'email' => 'hezhuanbao1@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$0ykww6YvJ3CtC73e8er.NOLSEv213gYsH6IIe1UqcPvc/zhnY00ce',
                'remember_token' => 'H0cru90KMI74BoOXKGoIFSo2I1AK2cUWU4QZLTDMdGbWOMZclRTKKjtZomqi',
                'device_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-01-02 20:02:37',
                'updated_at' => '2024-01-10 17:40:46',
            ),
            16 => 
            array (
                'id' => 151,
                'user_type' => 'employee',
                'employee_id' => 174,
                'branch_id' => 1,
                'division_id' => 4,
                'username' => 'Yusi',
                'name' => 'Yusi Apristia',
                'email' => 'yusiapristia@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$z2RAf.0HiFK5lDX9GkuSYOnc.KkqYub5oHYhMJbskBFQuG7U49g.O',
                'remember_token' => NULL,
                'device_token' => 'czQubtKvNvJ85tCMqz-oJo:APA91bGOIeLPMJyc301A6-MFhCW34OfO4l0CgpYtUBfgaKfkkVgmTDGQp_edhIza2XFDkotD3YBmPn90VVQfPCmPEJelMS8y-WPGlo6zP4mMh05ueTUQDzTXVtT9UUxQ-SrYiB0ikVS0',
                'deleted_at' => NULL,
                'created_at' => '2024-01-05 17:50:54',
                'updated_at' => '2024-01-11 20:49:50',
            ),
            17 => 
            array (
                'id' => 152,
                'user_type' => 'employee',
                'employee_id' => 183,
                'branch_id' => 1,
                'division_id' => 3,
                'username' => 'Ipung Salvota',
                'name' => 'Ipung Salvota',
                'email' => 'isalvota@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$qwPaJjB/jwxL2sSUeeYM3.8C4E54O2jSb2B9U9ZGiSbnchcp/yfZe',
                'remember_token' => NULL,
                'device_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-01-11 23:55:20',
                'updated_at' => '2024-01-11 23:55:20',
            ),
            18 => 
            array (
                'id' => 153,
                'user_type' => 'employee',
                'employee_id' => 19,
                'branch_id' => 1,
                'division_id' => 4,
                'username' => 'Agus Sudarsono',
                'name' => 'Agus Sudarsono',
                'email' => 'sudarsonoagus683@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$rG0a07pw3jGoR9EHrXmATOAbwKVng0clCdt3TWDoF73VIOWOzJDC2',
                'remember_token' => NULL,
                'device_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-02-12 23:58:47',
                'updated_at' => '2024-02-12 23:58:47',
            ),
            19 => 
            array (
                'id' => 154,
                'user_type' => 'employee',
                'employee_id' => 196,
                'branch_id' => 1,
                'division_id' => 4,
                'username' => 'CINDY RIKA PUSPITA',
                'name' => 'CINDY RIKA PUSPITA',
                'email' => 'CINDYPUSPITA04@GMAIL.COM',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Z6s3oje1Ds7/5g9D1Tk9..c.HfqDky2i2ehnUWsFo7Z0zCc5EWudK',
                'remember_token' => 'GzfOVWtj89FFFxHnwO33JsTxW0dCgPdlbGXiqSQbDDaQMcH09Ut6DHOJHstI',
                'device_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-02-21 20:56:03',
                'updated_at' => '2024-02-21 20:56:03',
            ),
            20 => 
            array (
                'id' => 155,
                'user_type' => 'employee',
                'employee_id' => 16,
                'branch_id' => 1,
                'division_id' => 4,
                'username' => 'HARYATI',
                'name' => 'HARYATI',
                'email' => 'haryati@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$mWAMUePpmouqJRgfhwA23ezqSQ94zaA7/bgnApXZwbANBXOsZx1ZC',
                'remember_token' => 'xWX105aRA8ouIFAU2vaxezPNz1wqk5fFHNhv7PYeL8tqHMab0vIEELhMN3iX',
                'device_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-02-26 16:45:06',
                'updated_at' => '2024-02-26 17:21:23',
            ),
        ));
        
        
    }
}