<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class WareHousesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('ware_houses')->delete();
        
        \DB::table('ware_houses')->insert(array (
            0 => 
            array (
                'id' => 1,
                'branch_id' => 4,
                'type' => 'trading',
                'nama' => 'SAMARINDA RETAIL',
                'deskripsi' => 'Retail dari TBBM / DEPOT Pertamina Samarinda Area:
Cendana
Palaran
Pendingin',
                'jalan' => NULL,
                'kota' => 'Samarinda',
                'provinsi' => 'Kalimantan TImur',
                'zip_code' => NULL,
                'longitude' => NULL,
                'created_at' => '2022-12-16 09:05:43',
                'updated_at' => '2023-05-24 20:05:04',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'branch_id' => 3,
                'type' => 'trading',
                'nama' => 'BANJARMASIN RETAIL',
                'deskripsi' => 'Retail dari TBBM/DEPOT Pertamina Area Kalsel
Banjarmasin
Kotabaru',
                'jalan' => NULL,
                'kota' => 'Banjarmasin',
                'provinsi' => 'Kalimantan Selatan',
                'zip_code' => NULL,
                'longitude' => NULL,
                'created_at' => '2022-12-16 09:05:43',
                'updated_at' => '2023-05-24 20:03:45',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'branch_id' => 1,
                'type' => 'trading',
                'nama' => 'SURABAYA RETAIL',
                'deskripsi' => 'Retail dari TBBM/Depot Pertamina Surabaya Area',
                'jalan' => NULL,
                'kota' => 'Surabaya',
                'provinsi' => 'Jawa Timur',
                'zip_code' => NULL,
                'longitude' => NULL,
                'created_at' => '2022-12-16 09:05:43',
                'updated_at' => '2023-05-24 20:04:37',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'branch_id' => 4,
                'type' => 'trading',
                'nama' => 'PHUNTSOG',
                'deskripsi' => 'OB PHUNTSOG',
                'jalan' => NULL,
                'kota' => 'Samarinda',
                'provinsi' => 'Kalimantan Timur',
                'zip_code' => NULL,
                'longitude' => NULL,
                'created_at' => '2022-12-16 09:05:43',
                'updated_at' => '2023-05-24 20:10:28',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'branch_id' => 1,
                'type' => 'general',
                'nama' => 'PT. USI PTE SBY',
                'deskripsi' => NULL,
                'jalan' => NULL,
                'kota' => NULL,
                'provinsi' => NULL,
                'zip_code' => NULL,
                'longitude' => NULL,
                'created_at' => '2023-03-22 00:59:31',
                'updated_at' => '2023-11-11 00:01:58',
                'deleted_at' => '2023-11-11 00:01:58',
            ),
            5 => 
            array (
                'id' => 6,
                'branch_id' => 1,
                'type' => 'general',
                'nama' => 'PT. USI PTE SMD',
                'deskripsi' => NULL,
                'jalan' => NULL,
                'kota' => NULL,
                'provinsi' => NULL,
                'zip_code' => NULL,
                'longitude' => NULL,
                'created_at' => '2023-03-22 00:59:57',
                'updated_at' => '2023-11-11 00:01:50',
                'deleted_at' => '2023-11-11 00:01:50',
            ),
            6 => 
            array (
                'id' => 7,
                'branch_id' => 1,
                'type' => 'general',
                'nama' => 'CV. PRIMA SOLUSI TEKNIK',
                'deskripsi' => NULL,
                'jalan' => NULL,
                'kota' => 'SURABAYA',
                'provinsi' => NULL,
                'zip_code' => NULL,
                'longitude' => NULL,
                'created_at' => '2023-03-22 06:22:11',
                'updated_at' => '2023-11-11 00:01:41',
                'deleted_at' => '2023-11-11 00:01:41',
            ),
            7 => 
            array (
                'id' => 8,
                'branch_id' => 1,
                'type' => 'general',
                'nama' => 'CV. SENTRAL JAYA TEHNIK',
                'deskripsi' => NULL,
                'jalan' => NULL,
                'kota' => NULL,
                'provinsi' => NULL,
                'zip_code' => NULL,
                'longitude' => NULL,
                'created_at' => '2023-03-22 17:54:12',
                'updated_at' => '2023-11-11 00:01:32',
                'deleted_at' => '2023-11-11 00:01:32',
            ),
            8 => 
            array (
                'id' => 9,
                'branch_id' => 1,
                'type' => 'general',
                'nama' => 'PT. USI PTS',
                'deskripsi' => NULL,
                'jalan' => NULL,
                'kota' => NULL,
                'provinsi' => NULL,
                'zip_code' => NULL,
                'longitude' => NULL,
                'created_at' => '2023-03-22 23:59:26',
                'updated_at' => '2023-11-11 00:01:23',
                'deleted_at' => '2023-11-11 00:01:23',
            ),
            9 => 
            array (
                'id' => 10,
                'branch_id' => 1,
                'type' => 'general',
                'nama' => 'Gondosuli Surabaya',
                'deskripsi' => NULL,
                'jalan' => 'Jl. Gondosuli No 8',
                'kota' => 'Surabaya',
                'provinsi' => 'Jawa Timur',
                'zip_code' => '60272',
                'longitude' => NULL,
                'created_at' => '2023-03-23 20:21:48',
                'updated_at' => '2023-11-11 00:01:11',
                'deleted_at' => '2023-11-11 00:01:11',
            ),
            10 => 
            array (
                'id' => 11,
                'branch_id' => 4,
                'type' => 'general',
                'nama' => 'Antasari Samarinda',
                'deskripsi' => NULL,
                'jalan' => 'Jl. Antasari No.66 B',
                'kota' => 'Samarinda',
                'provinsi' => 'Kalimantan Timur',
                'zip_code' => '75100',
                'longitude' => NULL,
                'created_at' => '2023-04-28 18:47:47',
                'updated_at' => '2023-11-11 00:00:57',
                'deleted_at' => '2023-11-11 00:00:57',
            ),
            11 => 
            array (
                'id' => 12,
                'branch_id' => 4,
                'type' => 'general',
                'nama' => 'Loakulu Samarinda',
                'deskripsi' => NULL,
                'jalan' => 'Jl. Bintuni Loakulu',
                'kota' => 'Samarinda',
                'provinsi' => 'Kalimantan Timur',
                'zip_code' => '75571',
                'longitude' => NULL,
                'created_at' => '2023-04-28 18:51:26',
                'updated_at' => '2023-11-11 00:00:44',
                'deleted_at' => '2023-11-11 00:00:44',
            ),
            12 => 
            array (
                'id' => 13,
                'branch_id' => 8,
                'type' => 'general',
            'nama' => 'PT. BME (Pabrik)',
                'deskripsi' => 'Pabrik Tenggarong',
                'jalan' => NULL,
                'kota' => 'Tenggarong',
                'provinsi' => 'Kalimantan',
                'zip_code' => NULL,
                'longitude' => NULL,
                'created_at' => '2023-05-23 00:56:08',
                'updated_at' => '2023-11-11 00:00:17',
                'deleted_at' => '2023-11-11 00:00:17',
            ),
            13 => 
            array (
                'id' => 14,
                'branch_id' => 4,
                'type' => 'trading',
                'nama' => 'OB PULAU JAYA',
                'deskripsi' => 'OB PULAU JAYA',
                'jalan' => 'Pangkalan USI Bintuni',
                'kota' => 'Samarinda',
                'provinsi' => 'Kalimantan Timur',
                'zip_code' => NULL,
                'longitude' => NULL,
                'created_at' => '2023-05-24 20:11:01',
                'updated_at' => '2023-05-24 20:11:44',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'branch_id' => 4,
                'type' => 'trading',
                'nama' => 'SPOB NORLHA 6',
                'deskripsi' => 'SPOB NORLHA 6',
                'jalan' => 'Pan',
                'kota' => 'Samarinda',
                'provinsi' => 'Kalimantan Timur',
                'zip_code' => NULL,
                'longitude' => NULL,
                'created_at' => '2023-05-24 20:12:47',
                'updated_at' => '2023-05-24 20:12:47',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'branch_id' => 4,
                'type' => 'trading',
                'nama' => 'SPOB NORLHA 5',
                'deskripsi' => 'SPOB NORLHA 5',
                'jalan' => NULL,
                'kota' => 'TARAKAN',
                'provinsi' => 'KALIMANTAN UTARA',
                'zip_code' => NULL,
                'longitude' => NULL,
                'created_at' => '2023-05-24 20:13:42',
                'updated_at' => '2023-05-24 20:13:42',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'branch_id' => 4,
                'type' => 'trading',
                'nama' => 'SPOB NORLHA 3',
                'deskripsi' => 'SPOB NORLHA 3',
                'jalan' => NULL,
                'kota' => 'Samarinda',
                'provinsi' => 'Kalimantan TImur',
                'zip_code' => NULL,
                'longitude' => NULL,
                'created_at' => '2023-05-24 20:14:57',
                'updated_at' => '2023-05-24 20:14:57',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'branch_id' => 4,
                'type' => 'trading',
                'nama' => 'SPOB NORLHA 2',
                'deskripsi' => 'SPOB NORLHA 2',
                'jalan' => NULL,
                'kota' => 'Samarinda',
                'provinsi' => 'Kalimantan Timur',
                'zip_code' => NULL,
                'longitude' => NULL,
                'created_at' => '2023-05-24 20:15:32',
                'updated_at' => '2023-05-24 20:15:32',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'branch_id' => 4,
                'type' => 'trading',
                'nama' => 'OB PRIMA SAKTI 128',
                'deskripsi' => 'OB PRIMA SAKTI 128',
                'jalan' => NULL,
                'kota' => 'Samarinda',
                'provinsi' => 'Kalimantan Timur',
                'zip_code' => NULL,
                'longitude' => NULL,
                'created_at' => '2023-05-24 20:16:27',
                'updated_at' => '2023-05-24 20:16:27',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'branch_id' => 7,
                'type' => 'trading',
                'nama' => 'BERAU RETAIL',
                'deskripsi' => NULL,
                'jalan' => NULL,
                'kota' => NULL,
                'provinsi' => NULL,
                'zip_code' => NULL,
                'longitude' => NULL,
                'created_at' => '2023-07-07 22:23:08',
                'updated_at' => '2023-07-07 22:23:08',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 22,
                'branch_id' => 1,
                'type' => 'general',
                'nama' => 'Gudang Reject',
                'deskripsi' => 'Gudang Barang Reject',
                'jalan' => NULL,
                'kota' => 'Surabaya',
                'provinsi' => 'Jawa Timur',
                'zip_code' => NULL,
                'longitude' => NULL,
                'created_at' => '2023-07-07 22:23:08',
                'updated_at' => '2023-07-07 22:23:08',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 23,
                'branch_id' => 1,
                'type' => 'trading',
                'nama' => 'Steenkool',
                'deskripsi' => NULL,
                'jalan' => NULL,
                'kota' => NULL,
                'provinsi' => NULL,
                'zip_code' => NULL,
                'longitude' => NULL,
                'created_at' => '2023-09-15 00:35:39',
                'updated_at' => '2023-09-15 00:35:39',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 24,
                'branch_id' => 1,
                'type' => 'trading',
                'nama' => 'Retail 2',
                'deskripsi' => NULL,
                'jalan' => NULL,
                'kota' => NULL,
                'provinsi' => NULL,
                'zip_code' => NULL,
                'longitude' => NULL,
                'created_at' => '2023-09-15 00:36:05',
                'updated_at' => '2023-09-15 00:36:05',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 25,
                'branch_id' => 1,
                'type' => 'trading',
                'nama' => 'BAKAMLA',
                'deskripsi' => 'BAKAMLA PROJECT NASIONAL',
                'jalan' => NULL,
                'kota' => NULL,
                'provinsi' => NULL,
                'zip_code' => NULL,
                'longitude' => NULL,
                'created_at' => '2023-11-15 00:27:35',
                'updated_at' => '2023-11-15 00:27:35',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 26,
                'branch_id' => 1,
                'type' => 'general',
                'nama' => 'SURABAYA',
                'deskripsi' => NULL,
                'jalan' => 'JALAN GONDOSULI 08',
                'kota' => 'SURBAYA',
                'provinsi' => 'JAWA TIMUR',
                'zip_code' => NULL,
                'longitude' => NULL,
                'created_at' => '2023-12-15 20:32:18',
                'updated_at' => '2023-12-15 20:32:18',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}