<?php

const AKA_PERMISSIONS = [
    'account-payable' => 'pembayaran hutang',
    'amortization' => 'amortisasi',
    'asset-category' => 'kategori aktiva tetap',
    'asset-disposition' => 'disposisi aktiva tetap',
    'asset-document-type' => 'tipe dokumen aktiva tetap',
    'bank-internal' => 'bank internal',
    'branch' => 'cabang',
    'cash-advance-payment' => 'pembayaran uang muka',
    'cash-advance-receive' => 'penerimaan uang muka',
    'cash-advance-return' => 'pengembalian uang muka',
    'cash-bond' => 'kas bon',
    'cash-bond-return' => 'pengembalian kas bon',
    'closing-period' => 'closing',
    'coa' => 'coa',
    'contract-extension' => 'pembaharuan kontrak',
    'currency' => 'currency',
    'customer' => 'customer',
    'customer-coa' => 'coa customer',
    'customer-receivable' => 'pelunasan piutang',
    'dashboard' => 'dashboard',
    'default-coa' => 'coa default',
    'degree' => 'gelar',
    'delivery-order' => 'delivery order trading',
    'delivery-order-general' => 'delivery order general',
    'depreciation' => 'depresiasi',
    'division' => 'divisi',
    'education' => 'pendidikan',
    'employee' => 'pegawai',
    'employment-status' => 'status kepegawaian',
    'evaluation' => 'assessment karyawan',
    'fleet' => 'kendaraan',
    'fund-submission' => 'pengajuan dana',
    'garage' => 'garasi',
    'hrd-assessment' => 'assesment hrd',
    'incoming-payment' => 'kas masuk',
    'invoice' => 'invoice trading',
    'invoice-general' => 'invoice general',
    'invoice-return' => 'retur penjualan',
    'invoice-trading' => 'invoice trading',
    'item' => 'item',
    'item-category' => 'kategori item',
    'item-price' => 'harga item',
    'item-receiving-report' => 'penerimaan barang',
    'item-receiving-report-general' => 'penerimaan barang general',
    'item-receiving-report-service' => 'penerimaan barang jasa',
    'item-receiving-report-trading' => 'lpb barang trading',
    'item-receiving-report-transport' => 'penerimaan barang transport',
    'item-subtitute' => 'barang pengganti',
    'journal' => 'jurnal',
    'labor-application' => 'lamaran kerja',
    'labor-demand' => 'permintaan tenaga kerja',
    'labor-transfer-form' => 'pemindahan tenaga kerja',
    'lease' => 'biaya dibayar dimuka',
    'leave' => 'cuti',
    'legality-document' => 'dokumen legal',
    'master-asset' => 'aktiva tetap',
    'master-evaluation' => 'master assessment',
    'master-hrd-assessment' => 'master assesment hrd',
    'master-user-assessment' => 'master assesment pegawai',
    'offering-letter' => 'penawaran kerja',
    'outgoing-payment' => 'kas keluar',
    'payroll' => 'penggajian',
    'payroll-period' => 'periode penggajian',
    'period' => 'periode harga',
    'permission-letter-employee' => 'izin pegawai',
    'position' => 'posisi',
    'presensi' => 'kehadiran',
    'price' => 'harga',
    'project' => 'project',
    'purchase-general' => 'pembelian general',
    'purchase-order' => 'pembelian',
    'purchase-request' => 'request pembelian',
    'purchase-request-general' => 'request pembelian general',
    'purchase-request-service' => 'request pembelian jasa',
    'purchase-request-transport' => 'request pembelian transport',
    'purchase-request-trading' => 'request pembelian trading',
    'purchase-return' => 'retur pembelian',
    'purchase-service' => 'pembelian jasa',
    'purchase-transport' => 'pembelian transport',
    'quotation' => 'penawaran harga',
    'quotation-add-on-type' => 'quotation add on type',
    'receivables-payment' => 'pelunasan piutang',
    'receive-payment' => 'giro masuk',
    'role' => 'akses',
    'sales-order' => 'sales order trading',
    'sales-order-general' => 'sales order general',
    'sh-number' => 'sh number',
    'specific-time-work-agreement' => 'perjanjian kerja waktu tertentu',
    'stock-adjustment' => 'penyesuaian stok',
    'stock-card' => 'kartu stok',
    'stock-card-general' => 'kartu stok general',
    'stock-card-trading' => 'kartu stok trading',
    'stock-card-value' => 'nilai stok',
    'stock-mutation' => 'mutasi stok',
    'stock-transfer' => 'transfer stok',
    'stock-transfer-receiving' => 'transfer stok penerimaan',
    'stock-usage' => 'pemakaian stok',
    'supplier-invoice' => 'tagihan supplier',
    'supplier-invoice-general' => 'tagihan supplier general',
    'tax' => 'pajak',
    'tax-reconciliation' => 'rekonsiliasi pajak',
    'tax-trading' => 'pajak trading',
    'transport-delivery-order' => 'surat jalan transport',
    'unit' => 'satuan',
    'user' => 'pengguna',
    'user-assessment' => 'assesment pegawai',
    'vendor' => 'vendor',
    'vendor-coa' => 'coa vendor',
    'ware-house' => 'gudang',
    'model' => 'master otorisasi',
    'closing-delivery-order-ship' => 'closing kapal',
    'salary-item' => 'komponen upah',
    'income-tax' => 'pajak penghasilan',
    'non-taxable-income' => 'penghasilan tidak kena pajak',
    'business-field' => 'bidang usaha',
    'report' => 'laporan',
    'master-letter' => 'master dokumen',
    'reset-leave' => 'cut off cuti',
    'mass-leave' => 'cuti bersama',
    'invoice-down-payment' => 'uang muka penjualan',
    'purchase-down-payment' => 'uang muka pembelian',
];

function getAkaPermission($permission)
{
    try {
        $explode_permission = explode(' ', $permission);
        $new_permission = $explode_permission[0] . ' ' . AKA_PERMISSIONS[$explode_permission[1]];

        return $new_permission;
    } catch (\Throwable $th) {
        return $permission;
    }
}

const master_permissions = [
    'branch',
    'role',
    'user',
    'user-activity',
    'education',
    'degree',
    'division',
    'employee',
    'position',
    'employment-status',
    'currency',
    'coa',
    'default-coa',
    'bank-internal',
    'project',
    'customer',
    'customer-coa',
    'sh-number',
    'vendor',
    'vendor-coa',
    'business-field',
    'item',
    'item-category',
    'item-price',
    'item-subtitute',
    'unit',
    'master-asset',
    'lease',
    'price',
    'tax',
    'tax-trading',
    'period',
    'quotation-add-on-type',
    'garage',
    'fleet',
    'ware-house',
    'master-evaluation',
    'master-hrd-assessment',
    'master-user-assessment',
    'asset-category',
    'asset-document-type',
    'model',
    'salary-item',
    'income-tax',
    'non-taxable-income',
    'master-letter',
    'reset-leave',
];
const penjualan_permissions = [
    'quotation',
    'sales-order',
    'sales-order-general',
    'delivery-order',
    'delivery-order-general',
    'invoice-general',
    'invoice-trading',
    'invoice-return',
    'invoice',
    'invoice-down-payment',

    'transport-delivery-order'
];
const pembelian_permissions = [
    'purchase-request',
    'purchase-request-service',
    'purchase-request-general',
    'purchase-request-transport',
    'purchase-request-trading',
    'purchase-return',
    'purchase-order',
    'purchase-transport',
    'purchase-service',
    'purchase-general',
    'purchase-down-payment',
    'item-receiving-report',
    'item-receiving-report-general',
    'item-receiving-report-service',
    'item-receiving-report-trading',
    'item-receiving-report-transport',
    'item-receiving-service',
    'item-receiving-trading',
];
const gudang_permissions = [
    'stock-card',
    'stock-card-value',
    'stock-card-general',
    'stock-card-trading',
    'stock-mutation',
    'stock-adjustment',
    'stock-usage',
    'stock-transfer-receiving',
    'stock-transfer',
    'closing-delivery-order-ship',
];

const hrd_permissions = [
    'labor-demand',
    'labor-application',
    'payroll-period',
    'payroll',
    'leave',
    'presensi',
    'permission-letter-employee',
    'contract-extension',
    'specific-time-work-agreement',
    'labor-transfer-form',
    'user-assessment',
    'hrd-assessment',
    'offering-letter',
    'legality-document',
    'evaluation'
];
const akuntansi_permissions = [
    'cash-advance-payment',
    'cash-advance-receive',
    'fund-submission',
    'receivables-payment',
    'account-payable',
    'asset-disposition',
    'cashbook',
    'cash-advance-return',
    'cash-bond',
    'cash-bond-return',
    'customer-receivable',
    'depreciation',
    'disposition',
    'closing-period',
    'tax-reconciliation',
    'journal',
    'supplier-invoice',
    'supplier-invoice-general',
    'outgoing-payment',
    'incoming-payment',
    'amortization',
    'receive-payment'
];
const report_permissions = [
    'profit-loss',
    'penjualan general report',
    'penjualan trading report',
];


// PERMISSION FOR SIDEBAR
const sidebar_master_permissions = [
    'view branch',
    'view master-evaluation',
    'view master-user-assessment',
    'view master-hrd-assessment',
    'view role',
    'view user',
    'view user-activity',
    'view education',
    'view degree',
    'view division',
    'view employee',
    'view position',
    'view employment-status',
    'view currency',
    'view coa',
    'view default-coa',
    'view bank-internal',
    'view project',
    'view customer',
    'view vendor',
    'view business-field',
    'view item',
    'view item-category',
    'view unit',
    'view asset-category',
    'view asset-document-type',
    'view master-asset',
    'view lease',
    'view period',
    'view price',
    'view tax',
    'view tax-trading',
    'view quotation-add-on-type',
    'view garage',
    'view fleet',
    'view ware-house',
    'view model',
    'view salary-item',
    'view income-tax',
    'view non-taxable-income',
    'view master-letter',
    'view reset-leave',
];

const sidebar_sales_permissions = [
    'view quotation',
    'view sales-order',
    'view sales-order-general',
    'view delivery-order',
    'view delivery-order-general',
    'view invoice-trading',
    'view invoice-general',
    'view invoice-down-payment',
    'view invoice-return',
    'penjualan general report',
    'penjualan trading report'
];

const sidebar_purchase_permissions = [
    'view purchase-request',
    'view purchase-request-service',
    'view purchase-request-general',
    'view purchase-request-transport',
    'view purchase-retur',
    'view purchase-order',
    'view purchase-transport',
    'view purchase-service',
    'view purchase-general',
    'view purchase-down-payment',
    'view item-receiving-report',
    'view item-receiving-report-general',
    'view item-receiving-service',
    'view item-receiving-trading',
    'view item-receiving-report-transpor',
    'view purchase-return',
    'purchase request report',
    'purchase order report',
    'purchase order trading report',
    'purchase order general report',
    'purchase order service report',
    'purchase order transport report',
];

const sidebar_warehouse_permissions = [
    'view stock-card',
    'view stock-card-value',
    'view stock-mutation',
    'view stock-adjustment',
    'view stock-usage',
    'view stock-transfer',
    'view closing-delivery-order-ship',
    'warehouse report'
];

const sidebar_hrd_permissions = [
    'view labor-demand',
    'view labor-application',
    'view hrd-assessment',
    'view user-assessment',
    'view offering-letter',
    'view contract-extension',
    'view specific-time-work-agreement',
    'view labor-transfer-form',
    'view presensi',
    'view leave',
    'view permission-letter-employee',
    'view payroll-period',
    'view payroll',
    'view evaluation',
    'view legality-document',
    'hrd report',
    'view mass-leave',
];

const sidebar_finance_permissions = [
    'view cash-advance-receive',
    'view receive-payment',
    'view receivables-payment',
    'view incoming-payment',
    'view cash-advance-return',
    'view fund-submission',
    'view account-payable',
    'view outgoing-payment',
    'view cash-advance-payment',
    'view supplier-invouce',
    'view supplier-invoice-general',
    'view cash-bond',
    'view cash-bond-return',
    'view tax-reconciliation',
    'view asset-disposition',
    'view depreciation',
    'view amortization',
    'view closing-period',
    'view journal',
    'finance report',
    'accounting report',
    'cashier report'
];
